INSERT INTO LOGIN_DOMAIN VALUES (1, 1, 'Localhost Moodle', 'http://localhost/moodle/wspp/service_pp.php');
INSERT INTO LOGIN_DOMAIN VALUES (2, 1, 'IP Moodle', 'http://192.168.1.52/moodle/wspp/service_pp.php');
INSERT INTO LOGIN_DOMAIN VALUES (3, 1, 'Invalid Moodle', 'http://localhost-invalid/moodle/wspp/service_pp.php');
INSERT INTO LOGIN_DOMAIN VALUES (4, 1, 'Internal', null);

INSERT INTO PRINCIPAL (ID, INSTANCE_TYPE, VERSION, NAME) VALUES (1, 'Role', 1, 'ADMIN');
INSERT INTO PRINCIPAL (ID, INSTANCE_TYPE, VERSION, NAME) VALUES (2, 'Role', 1, 'TEACHER');
INSERT INTO PRINCIPAL (ID, INSTANCE_TYPE, VERSION, NAME) VALUES (3, 'Role', 1, 'STUDENT');

INSERT INTO PRINCIPAL (ID, INSTANCE_TYPE, VERSION, USERNAME) VALUES (4, 'User', 1, 'rec.am');
INSERT INTO IDENTIFICATION (ID, INSTANCE_TYPE, VERSION, PASSWORD, KEY_USER) VALUES (1, 'Login', 1, MD5('pass'), 4);

INSERT INTO PRINCIPALS_ASSOCIATION (KEY_PARENT, KEY_CHILD) VALUES (1, 4);