version: '3.5'
services:
  elab-client-webswing:
    image: ${repo}/${simplifiedGroupId}/webswing-${webswing.version}-${openjdk.version}:${project.version}
    restart: always
    environment:
      XDG_RUNTIME_DIR: '/opt/webswing/.cache/xdgr'
      WEBSWING_SECRET_FILE: "/run/secrets/webswing-connection.secret"
      WEBSWING_ADMIN_HOST: "webswing-admin"
      WEBSWING_ADMIN_PORT: "8080"
    secrets:
      - webswing-connection.secret
    volumes:
      - ws-logs:/opt/webswing/logs:rw
  
  # Standalone webswing admin console
  # webswing-admin:
  #   image: ${repo}/${simplifiedGroupId}/base-images/webswing-admin-${webswing.version}-${openjdk.version}:${project.version}
  #   restart: always
  #   environment:
  #     WEBSWING_HOST: "elab-client-webswing"
  #     WEBSWING_PORT: "8080"
  #     WEBSWING_WEBSOCKET_PORT: "8080"
  #     WEBSWING_SECRET_FILE: "/run/secrets/webswing-connection.secret"
  #   secrets:
  #     - webswing-connection.secret
  #   volumes:
  #     - ws-logs:/var/opt/logs:ro

  elab-server-payara:
    image: ${repo}/${simplifiedGroupId}/payara-${payara.docker.version}:${project.version}
    environment:
      jvm-options: '-XX\:+UnlockExperimentalVMOptions:-XX\:+UseContainerSupport:-XX\:MaxRAMPercentage=1:-Xms1g:-Xmx2g'
      REC_DB_HOST: 'rec-database'
      REC_DB_PORT: '3306'
      GFTIMER_DB_HOST: 'gftimer-database'
      GFTIMER_DB_PORT: '3306'
      MULTICAST_HOST: 'elab-multicast'
      MULTICAST_PORT: '9001'
    restart: unless-stopped
    secrets:
      - as_mail.secret
      - as_recdb.secret
      - as_gftimerdb.secret
    depends_on:
      - rec-database
      - elab-multicast
      - gftimer-database

  rec-database:
    image: docker-thirdparty.linkare.com/mysql:5.7.25
    secrets:
      - rdb.secret
      - dbrec.secret
    environment:
      MYSQL_ROOT_PASSWORD_FILE: '/run/secrets/rdb.secret'
      MYSQL_USER: 'rec'
      MYSQL_PASSWORD_FILE: '/run/secrets/dbrec.secret'
      MYSQL_DATABASE: 'rec'
    volumes:
      - db-rec:/var/lib/mysql:rw
    restart: unless-stopped

  gftimer-database:
    image: docker-thirdparty.linkare.com/mysql:5.7.25
    secrets:
      - rdb.secret
      - dbgftimer.secret
    environment:
      MYSQL_ROOT_PASSWORD_FILE: '/run/secrets/rdb.secret'
      MYSQL_USER: 'gftimer'
      MYSQL_PASSWORD_FILE: '/run/secrets/dbgftimer.secret'
      MYSQL_DATABASE: 'gftimer'
    volumes:
      - db-gftimer:/var/lib/mysql:rw
    restart: unless-stopped

  elab-multicast:
    image: ${repo}/${simplifiedGroupId}/base-images/openjdk-${openjdk.docker.version}:${project.version}
    healthcheck:
      test: pgrep java
      interval: 30s
      timeout: 1s
      retries: 3
      start_period: 30s
    restart: unless-stopped

secrets:
  dbrec.secret: {}
  dbgftimer.secret: {}
  rdb.secret: {}
  as_mail.secret: {}
  as_recdb.secret: {}
  as_gftimerdb.secret: {}
  webswing-connection.secret: {}
 
volumes:
  db-rec:
    name: db-rec
  db-gftimer:
    name: db-gftimer
  ws-logs:
    name: webswing-logs
