version: '3.5'
services:
  elab-multicast:
    container_name: rec.multicast
    ports:
      - "25001:25001"
      - "9001:9001"
    healthcheck:
      test: pgrep java
      interval: 30s
      timeout: 1s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    environment:
      APPNAME: 'pendulum'
      APPUSER: 'elab'
      WORKDIR: '/home/elab/rec-deployment/pendulum'
      LABORATORY_NAMES: 'pendulum'
    image: ${repo}/${simplifiedGroupId}/${laboratory}/rec.multicast-${openjdk.version}:${project.version}

  elab-client-webswing:
    container_name: rec.client
    image: ${repo}/${simplifiedGroupId}/${laboratory}/webswing-${webswing.version}-${openjdk.version}:${project.version}
    restart: unless-stopped
    ports:
      - "28080:8080"
    environment:
      XDG_RUNTIME_DIR: '/opt/webswing/.cache/xdgr'
      WEBSWING_ADMIN_CONSOLE_URL: 'http://localhost:38080'
    labels:
      # HTTP (80)
      - "traefik.http.routers.webswing-http.entrypoints=web"
      - "traefik.http.routers.webswing-http.rule=PathPrefix(`/`)"
      - "traefik.http.routers.webswing-http.middlewares=webswing-http-redir"
      - "traefik.http.services.webswing-http.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.webswing-http-redir.redirectscheme.scheme=https"
      # HTTPS (443)
      - "traefik.http.routers.webswing-https.entrypoints=web-secure"
      - "traefik.http.routers.webswing-https.rule=PathPrefix(`/`)"
      - "traefik.http.routers.webswing-https.tls=true"

  webswing-admin:
    container_name: rec.client-admin
    image: ${repo}/${simplifiedGroupId}/${laboratory}/webswing-admin-${webswing.version}-${openjdk.version}:${project.version}
    restart: unless-stopped
    ports:
      - "38080:8080"
    environment:
      WEBSWING_HOST: elab-client-webswing
      WEBSWING_WEBSOCKET_PORT: 8080
      WEBSWING_SHARED_LOG_DIR: /var/opt/logs
      WEBSWING_PUBLIC_URL: http://localhost:28080

  reverse-proxy:
    image: ${repo}/${simplifiedGroupId}/${laboratory}/traefik-${traefik.version}:${project.version}