version: '3.5'
services:
  rec-database:
    volumes:
      - /home/linkare/rec-schema.sql:/docker-entrypoint-initdb.d/rec-schema.sql
      - /home/linkare/gf_timer-schema.sql:/docker-entrypoint-initdb.d/gf_timer-schema.sql
  elab-multicast:
    ports:
      # Basic
      - "25001:25001"
      - "9001:9001"
      # Intermediate
      - "25002:25002"
      - "9002:9002"
      # Advanced
      - "25003:25003"
      - "9003:9003"
      
secrets:
   dbrec.secret:
     file: /home/linkare/rec-db.secret
   rdb.secret:
     file: /home/linkare/root-db.secret
   as_mail.secret:
     file: /home/linkare/asadmin_mail.secret
   as_recdb.secret:
     file: /home/linkare/asadmin_recdb.secret
   webswing-connection.secret:
     file: /home/linkare/webswing-connection.secret