version: '3.5'
services:
  reverse-proxy:
    container_name: rec.proxy
    image: ${hub}/${simplifiedGroupId}/base-images/traefik-${traefik.version}:${project.version}
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.web-secure.address=:443 #Declares the web-secure entrypoint in Traefik
      - --providers.docker=true
      - --api.insecure=true
    ports:
      - "80:80"
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    restart: unless-stopped
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock:ro

  nginx-fileserver:
    container_name: rec.static
    image: ${public.repo}/nginx:1.19.6
    restart: unless-stopped
    volumes:
      # Allow real-time refresh (with rec.web build)
      - rec-static-files:/usr/share/nginx/html/rec.web/client/etc:ro
    labels:
      # HTTP (80)
      - "traefik.http.routers.nginx-http.entrypoints=web"
      - "traefik.http.routers.nginx-http.rule=PathPrefix(`/rec.web/client`)"
      - "traefik.http.routers.nginx-http.middlewares=nginx-redir-http"
      - "traefik.http.services.nginx-http.loadbalancer.server.port=80"
      - "traefik.http.middlewares.nginx-redir-http.redirectscheme.scheme=https"
      # HTTPS (443)
      - "traefik.http.routers.nginx-https.entrypoints=web-secure"
      - "traefik.http.routers.nginx-https.rule=PathPrefix(`/rec.web/client`)"
      - "traefik.http.routers.nginx-https.tls=true"

  elab-client-webswing:
    container_name: rec.client
    image: ${hub}/${simplifiedGroupId}/rec.client-${webswing.version}-${openjdk.version}:${project.version}
    restart: unless-stopped
    environment:
      XDG_RUNTIME_DIR: '/opt/webswing/.cache/xdgr'
    labels:
      # HTTP (80)
      - "traefik.http.routers.webswing-http.entrypoints=web"
      - "traefik.http.routers.webswing-http.rule=PathPrefix(`/`)"
      - "traefik.http.routers.webswing-http.middlewares=webswing-redir-http"
      - "traefik.http.services.webswing-http.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.webswing-redir-http.redirectscheme.scheme=https"
      # HTTPS (443)
      - "traefik.http.routers.webswing-https.entrypoints=web-secure"
      - "traefik.http.routers.webswing-https.rule=PathPrefix(`/`)"
      - "traefik.http.routers.webswing-https.tls=true"
    volumes:
      - rec-static-files:/opt/webswing/apps/webapps/elab/etc:rw

  webswing-admin:
    container_name: rec.client-admin
    image: ${hub}/${simplifiedGroupId}/rec.client-admin-${webswing.version}-${openjdk.version}:${project.version}
    restart: unless-stopped
    environment:
      WEBSWING_HOST: elab-client-webswing
      WEBSWING_WEBSOCKET_PORT: 8080
      WEBSWING_SHARED_LOG_DIR: /var/opt/logs
      WEBSWING_PUBLIC_URL: https://elab.dev.linkare.com

  elab-multicast:
    container_name: rec.multicast
    image: ${hub}/${simplifiedGroupId}/rec.multicast-${openjdk.version}:${project.version}
    healthcheck:
      test: pgrep java
      interval: 30s
      timeout: 1s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    ports:
      # Basic
      - "25001:25001"
      - "9001:9001"
      # Intermediate
      - "25002:25002"
      - "9002:9002"
      # Advanced
      - "25003:25003"
      - "9003:9003"

volumes:
  rec-static-files: {}
