version: '3.5'
services:
  elab-multicast:
    container_name: rec-multicast
    ports:
      #- "25001:25001" # Only needed if rec.web outside this server
      - "9001:9001"
    networks:
      default: 
        aliases:
          - elab-dev.vps.tecnico.ulisboa.pt

  rec-database:
    container_name: rec-db
    volumes:
      - /home/linkare/rec-schema.sql:/docker-entrypoint-initdb.d/rec-schema.sql:rw
      - /home/linkare/gf_timer-schema.sql:/docker-entrypoint-initdb.d/gf_timer-schema.sql:rw

  elab-client-webswing:
    container_name: rec-client
  
  elab-server-payara:
    container_name: rec-web

  reverse-proxy:
    container_name: rec-proxy

  webswing-admin:
    container_name: rec-client-admin
    environment:
      WEBSWING_PUBLIC_URL: https://elab-dev.vps.tecnico.ulisboa.pt

secrets:
  as_mail.secret:
    file: /home/linkare/asadmin_mail.secret
  as_recdb.secret:
    file: /home/linkare/asadmin_recdb.secret
  dbrec.secret:
    file: /home/linkare/rec-db.secret
  rdb.secret:
    file: /home/linkare/root-db.secret

volumes:
  db-rec:
    name: db-rec
