version: '3.5'
services:
  elab-multicast:
    ports:
      # Basic
      - "25001:25001"
      - "9001:9001"
      # Intermediate
      - "25002:25002"
      - "9002:9002"
      # Advanced
      - "25003:25003"
      - "9003:9003"
      
secrets:
   dbrec.secret:
     file: /home/linkare/secrets/rec-db.secret
   rdb.secret:
     file: /home/linkare/secrets/root-db.secret
   as_mail.secret:
     file: /home/linkare/secrets/asadmin_mail.secret
   as_recdb.secret:
     file: /home/linkare/secrets/asadmin_recdb.secret