version: '3.5'
services:
  elab-client-webswing:
    image: ${repo}/${simplifiedGroupId}/rec.client-${webswing.version}-${openjdk.version}:${project.version}
    ports:
      - "18080:8080"
      - "18000:8000"
  
  webswing-admin:
    image: ${repo}/${simplifiedGroupId}/rec.client-admin-${webswing.version}-${openjdk.version}:${project.version}
    ports:
      - "38080:8080"
      - "38000:8000"

  elab-server-payara:
    image: ${repo}/${simplifiedGroupId}/rec.web-${payara.docker.version}:${project.version}
    ports:
      - "28080:8080"
      - "24848:4848"
      - "29009:9009"
    environment:
      DEVELOPMENT_MODE: ${development.mode}
      PAYARA_ARGS: "--debug"
    volumes:
      # Allow real-time refresh (with rec.web build)
      - ${project.build.directory}/resources/autodeploy:/autodeploy

  rec-database:
    image: ${repo}/${simplifiedGroupId}/rec.database:${project.version}
    ports:
      - "13306:3306"
    volumes:
     - ${project.build.directory}/resources/rec-schema.sql:/docker-entrypoint-initdb.d/rec-schema.sql
     - ${project.build.directory}/resources/gf_timer-schema.sql:/docker-entrypoint-initdb.d/gf_timer-schema.sql
    #restart: "none"

  elab-multicast:
    image: ${repo}/${simplifiedGroupId}/rec.multicast-${openjdk.version}:${project.version}
    ports:
      # Basic
      - "25001:25001"
      - "9001:9001"
      # Intermediate
      - "25002:25002"
      - "9002:9002"
      # Advanced
      - "25003:25003"
      - "9003:9003"
  
  elab-hardware-server:
    image: ${repo}/${simplifiedGroupId}/base-images/openjdk-${openjdk.docker.version}:${project.version}
    healthcheck:
      test: pgrep java
      interval: 30s
      timeout: 1s
      retries: 3
      start_period: 30s
    depends_on:
      - elab-multicast
    volumes:
      - ${project.build.directory}/resources/hardwareserver:/startup.d/

  # elab-streamer-server:
  #   image: ${repo}/${simplifiedGroupId}/base-images/streamer:${project.version}
  #   ports:
  #     - "8554:8554"
  
  nginx-fileserver:
    image: docker-thirdparty.linkare.com/nginx:1.19.6
    volumes:
      #- ${project.build.directory}/resources/etc:/www/data:ro
      # Allow real-time refresh (with rec.web build)
      - ${project.parent.basedir}/rec.web/target/rec.web/client/etc:/usr/share/nginx/html/rec.web/client/etc:ro
    labels:
      # HTTP (80)
      - "traefik.http.routers.nginx-http.entrypoints=web"
      - "traefik.http.routers.nginx-http.rule=PathPrefix(`/rec.web/client`)"
      - "traefik.http.routers.nginx-http.middlewares=nginx-redir-http"
      - "traefik.http.services.nginx-http.loadbalancer.server.port=80"
      - "traefik.http.middlewares.nginx-redir-http.redirectscheme.scheme=https"
      # HTTPS (443)
      - "traefik.http.routers.nginx-https.entrypoints=web-secure"
      - "traefik.http.routers.nginx-https.rule=PathPrefix(`/rec.web/client`)"
      - "traefik.http.routers.nginx-https.tls=true"

  # upgrade-db:
  #   image: ${repo}/${simplifiedGroupId}/rec.upgrade-db-${liquibase.version}:${project.version}
  #   secrets:
  #     - dbrec.secret
  #   environment:
  #     - TZ=Europe/Lisbon
  #     - TARGET_DB=rec
  #     - DB_HOST=rec-database
  #     - DB_PORT=3306
  #     - DB_USER=rec
  #     - DB_PASS_FILE=/run/secrets/dbrec.secret
  #     #- DUMP_SQL=""
  #     #- FORCE_UNLOCK=""
  #     #- RESET_CKSUMS=""
  #     - LOGGING_LEVEL=info
  #     - CHANGELOG_FILE=/changelog/db.changelog-master.xml

  reverse-proxy:
    image: ${repo}/${simplifiedGroupId}/base-images/traefik-${traefik.version}:${project.version}
      
secrets:
   dbrec.secret:
     file: ${project.build.directory}/resources/rec-db.secret
   rdb.secret:
     file: ${project.build.directory}/resources/root-db.secret
   as_mail.secret:
     file: ${project.build.directory}/resources/asadmin_mail.secret
   as_recdb.secret:
     file: ${project.build.directory}/resources/asadmin_recdb.secret
