version: '3.5'
services:
  elab-client-webswing:
    ports:
      - "18080:8080"
      - "18000:8000"
    ##restart: "none"
    ##privileged: true
    #volumes:
    #  #- /var/run/docker.sock:/var/run/docker.sock
    #  - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket

  # Standalone webswing admin console
  # webswing-admin:
  #   ports:
  #     - "38080:8080"
  #   environment:
  #     WEBSWING_PUBLIC_URL: "http://localhost:18080"

  elab-server-payara:
    ports:
      - "28080:8080"
      - "24848:4848"

  rec-database:
    ports:
      - "13306:3306"
    volumes:
      - ${project.build.directory}/resources/rec-schema.sql:/docker-entrypoint-initdb.d/rec-schema.sql
    #restart: "none"

  gftimer-database:
    ports:
      - "23306:3306"
    volumes:
      - ${project.build.directory}/resources/gf_timer-schema.sql:/docker-entrypoint-initdb.d/gf_timer-schema.sql
    #restart: "none"

  elab-multicast:
    ports:
      - "25001:25001"
      - "9001:9001"
    volumes:
      - ${project.build.directory}/resources/multicast:/startup.d/
  
  elab-hardware-server:
    #ports:
    #  - "?:?"
    volumes:
      - ${project.build.directory}/resources/hardwareserver:/startup.d/

  elab-streamer-server:
    ports:
      - "8554:8554"
      
secrets:
   dbrec.secret:
     file: ${project.build.directory}/resources/rec-db.secret
   dbgftimer.secret:
     file: ${project.build.directory}/resources/gftimer-db.secret
   rdb.secret:
     file: ${project.build.directory}/resources/root-db.secret
   as_mail.secret:
     file: ${project.build.directory}/resources/asadmin_mail.secret
   as_recdb.secret:
     file: ${project.build.directory}/resources/asadmin_recdb.secret
   as_gftimerdb.secret:
     file: ${project.build.directory}/resources/asadmin_gftimerdb.secret
   webswing-connection.secret:
     file: ${project.build.directory}/resources/webswing-connection.secret