/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ApparatusSelectBox.java
 *
 * Created on 20/Abr/2009, 11:06:21
 */

package com.linkare.rec.impl.newface.component;

import java.util.logging.Logger;

import org.jdesktop.application.Action;

import com.linkare.rec.impl.newface.ReCApplication;
import com.linkare.rec.impl.newface.ReCFrameView;

/**
 * 
 * @author Henrique Fernandes
 */
public class ApparatusSelectBox extends AbstractContentPane {

    private static final Logger log = Logger.getLogger(ApparatusSelectBox.class.getName());

    private ReCApplication recApplication = ReCApplication.getApplication();

    /** Creates new form ApparatusSelectBox */
    public ApparatusSelectBox() {
	initComponents();

	progressCicle.setBusyIcons(ReCFrameView.busyIcons);
    }

    public ApparatusCombo getApparatusCombo() {
	return apparatusCombo;
    }

    public FlatButton getButtonToggleEnter() {
	return btnToggleEnter;
    }

    //    public void setProgressVisible(boolean visible) {
    //        progressCicle.setVisible(visible);
    //        progressCicle.setState(visible ? State.RUNNING : State.IDLE);
    //    }

    /**
     * @return the progressCicle
     */
    public com.linkare.rec.impl.newface.component.ProgressCicle getProgressCicle() {
	return progressCicle;
    }

    public void toggleApparatusStateActionData(boolean connected) {

	javax.swing.Action toggleApparatusStateAction = getContext().getActionMap(ReCApplication.class,
		getRecApplication()).get("toggleApparatusState");

	toggleApparatusStateAction.putValue(javax.swing.Action.NAME, getContext().getResourceMap().getString(
		"toggleApparatusState" + (connected ? "" : "Disconnect") + ".Action.text"));
	toggleApparatusStateAction.putValue(javax.swing.Action.SHORT_DESCRIPTION, getContext().getResourceMap()
		.getString("toggleApparatusState" + (connected ? "" : "Disconnect") + ".Action.shortDescription"));

	if (connected) {
	    btnToggleEnter.setGradientBottom(FlatButton.GRADIENTBOTTOM_OFF);
	    btnToggleEnter.setGradientTop(FlatButton.GRADIENTTOP_OFF);
	    btnToggleEnter.setForeground(FlatButton.FOREGROUND_OFF);
	    btnToggleEnter.setBorderColor(FlatButton.COLORBORDER_OFF);
	} else {
	    btnToggleEnter.setGradientBottom(FlatButton.GRADIENTBOTTOM_ON);
	    btnToggleEnter.setGradientTop(FlatButton.GRADIENTTOP_ON);
	    btnToggleEnter.setForeground(FlatButton.FOREGROUND_ON);
	    btnToggleEnter.setBorderColor(FlatButton.COLORBORDER_ON);
	}

	btnToggleEnter.setAction(toggleApparatusStateAction);

	// TODO this is fixing the focus repaint problem. Find a better way.
	repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

	lblChooseApparatus = new javax.swing.JLabel();
	apparatusCombo = new com.linkare.rec.impl.newface.component.ApparatusCombo();
	btnToggleEnter = new com.linkare.rec.impl.newface.component.FlatButton();
	progressCicle = new com.linkare.rec.impl.newface.component.ProgressCicle();

	setName("Form"); // NOI18N

	lblChooseApparatus.setFont(lblChooseApparatus.getFont().deriveFont(
		lblChooseApparatus.getFont().getStyle() | java.awt.Font.BOLD, 11));
	org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(
		com.linkare.rec.impl.newface.ReCApplication.class).getContext()
		.getResourceMap(ApparatusSelectBox.class);
	lblChooseApparatus.setText(resourceMap.getString("lblChooseApparatus.text")); // NOI18N
	lblChooseApparatus.setName("lblChooseApparatus"); // NOI18N

	apparatusCombo.setModel(getRecApplication().getApparatusComboBoxModel());
	apparatusCombo.setName("apparatusCombo"); // NOI18N

	javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(
		com.linkare.rec.impl.newface.ReCApplication.class).getContext().getActionMap(ApparatusSelectBox.class,
		this);
	btnToggleEnter.setAction(actionMap.get("toggleApparatusState")); // NOI18N
	btnToggleEnter.setText(resourceMap.getString("btnToggleEnter.text")); // NOI18N
	btnToggleEnter.setFont(btnToggleEnter.getFont().deriveFont(
		btnToggleEnter.getFont().getStyle() | java.awt.Font.BOLD));
	btnToggleEnter.setName("btnToggleEnter"); // NOI18N

	progressCicle.setIdleIcon(resourceMap.getIcon("progressCicle.idleIcon")); // NOI18N
	progressCicle.setName("progressCicle"); // NOI18N

	javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
	this.setLayout(layout);
	layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
		layout.createSequentialGroup().addContainerGap().addGroup(
			layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				apparatusCombo, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
				.addComponent(lblChooseApparatus).addGroup(
					layout.createSequentialGroup().addComponent(btnToggleEnter,
						javax.swing.GroupLayout.PREFERRED_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(
						javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(
						progressCicle, javax.swing.GroupLayout.PREFERRED_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE))).addContainerGap()));
	layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
		layout.createSequentialGroup().addContainerGap().addComponent(lblChooseApparatus).addPreferredGap(
			javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(apparatusCombo,
			javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
			javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(
			javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addGroup(
			layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addComponent(
				progressCicle, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(btnToggleEnter,
				javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
				Short.MAX_VALUE)).addContainerGap(62, Short.MAX_VALUE)));

	apparatusCombo.getAccessibleContext().setAccessibleName(
		resourceMap.getString("apparatusCombo.AccessibleContext.accessibleName")); // NOI18N
	apparatusCombo.getAccessibleContext().setAccessibleDescription(
		resourceMap.getString("apparatusCombo.AccessibleContext.accessibleDescription")); // NOI18N
    }// </editor-fold>//GEN-END:initComponents

    @Action
    public void toggleApparatusState() {
	recApplication.toggleApparatusState();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.linkare.rec.impl.newface.component.ApparatusCombo apparatusCombo;
    private com.linkare.rec.impl.newface.component.FlatButton btnToggleEnter;
    private javax.swing.JLabel lblChooseApparatus;
    private com.linkare.rec.impl.newface.component.ProgressCicle progressCicle;
    // End of variables declaration//GEN-END:variables

}
