package com.linkare.rec.impl.newface.component;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 * 
 * @author João Florindo
 */
public class ExpHistoryPanel extends javax.swing.JPanel {

	private ExperimentHistoryUINode expHist = null;

	public ExpHistoryPanel(ExperimentHistoryUINode expHist) {
		this.expHist = expHist;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
	 * content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		lAbrir = new JButton("Abrir");
		lConf = new JButton("Configurar");
		lApagar = new JButton("Apagar");
		lTitle = new JLabel("Experiencia");
		jPaneOps = new JPanel();

		jPaneOps.setLayout(new GridBagLayout());
		GridBagConstraints gridBagConstraints = null;

		lTitle.setText(expHist.getApparatusName());
		lTitle.setIcon(expHist.getApparatusIcon());
		System.out.println("............." + expHist.getApparatusName() + expHist.getApparatusIcon());
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.gridwidth = 3;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
		gridBagConstraints.insets = new java.awt.Insets(10, 2, 5, 2);
		jPaneOps.add(lTitle, gridBagConstraints);

		lAbrir.setText("<HTML><U>Abrir</U> | </HTML>");
		lAbrir.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				btnExpAbrirActionPerformed(e);

			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
		gridBagConstraints.insets = new java.awt.Insets(0, 2, 5, 2);
		jPaneOps.add(lAbrir, gridBagConstraints);

		lConf.setText("<HTML> <U>Config.</U> | </HTML>");
		lConf.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				btnExpConfActionPerformed(e);

			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
		gridBagConstraints.insets = new java.awt.Insets(0, 2, 5, 2);
		jPaneOps.add(lConf, gridBagConstraints);

		lApagar.setText("<HTML> <U>Apagar</U> </HTML>");
		lApagar.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				btnExpApagarActionPerformed(e);

			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
		gridBagConstraints.insets = new java.awt.Insets(0, 2, 5, 2);
		jPaneOps.add(lApagar, gridBagConstraints);

	}// </editor-fold>//GEN-END:initComponents

	private void btnExpAbrirActionPerformed(java.awt.event.ActionEvent evt) {

	}

	private void btnExpConfActionPerformed(java.awt.event.ActionEvent evt) {

	}

	private void btnExpApagarActionPerformed(java.awt.event.ActionEvent evt) {

	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private JButton lAbrir = null;
	private JButton lConf = null;
	private JButton lApagar = null;
	private JLabel lTitle = null;
	private JPanel jPaneOps = null;
	// End of variables declaration//GEN-END:variables

}
