/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VideoBox.java
 *
 * Created on 20/Abr/2009, 11:39:32
 */

package com.linkare.rec.impl.newface.component;

import java.awt.Canvas;
import java.awt.Color;

/**
 *
 * @author iies-consultor922
 */
public class VideoBox extends AbstractContentPane {

    /** Creates new form VideoBox */
    public VideoBox() {
        initComponents();
        videoCanvas.setVisible(false);
    }

    /**
     * Creates the video canvas where the video will be displayed and adds the
     * component to the VideoBox. 
     */
    public void initializeVideoOutput() {

        videoCanvas.setSize(videoPanel.getWidth(), videoPanel.getHeight());
        videoCanvas.setVisible(true);
        videoCanvas.setBackground(Color.BLACK);
    }

    /**
     * Remove the Canvas from the UI when not needed.
     */
    public void destroyVideoOutput() {

        videoCanvas.setVisible(false);
    }

    /**
     * Returns the component where the video will be displayed. The return
     * of this method can be null, so a check for null is needed after
     * invocation.
     * @return
     */
    public Canvas getVideoOutput() {
        return videoCanvas;
    }

    /**
     * Resizes the VideoOutput.
     * @param width
     * @param height
     */
    public void changeVideoOutputSize(int width, int height) {

        videoPanel.setSize(width, height);
        if (videoCanvas != null)
            videoCanvas.setSize(width, height);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblVideo = new javax.swing.JLabel();
        videoPanel = new javax.swing.JPanel();
        videoCanvas = new java.awt.Canvas();

        setName("Form"); // NOI18N

        lblVideo.setFont(lblVideo.getFont().deriveFont(lblVideo.getFont().getStyle() | java.awt.Font.BOLD, 11));
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.linkare.rec.impl.newface.ReCApplication.class).getContext().getResourceMap(VideoBox.class);
        lblVideo.setText(resourceMap.getString("lblVideo.text")); // NOI18N
        lblVideo.setName("lblVideo"); // NOI18N

        videoPanel.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        videoPanel.setName("videoPanel"); // NOI18N

        videoCanvas.setName("videoCanvas"); // NOI18N

        javax.swing.GroupLayout videoPanelLayout = new javax.swing.GroupLayout(videoPanel);
        videoPanel.setLayout(videoPanelLayout);
        videoPanelLayout.setHorizontalGroup(
            videoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(videoCanvas, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
        );
        videoPanelLayout.setVerticalGroup(
            videoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(videoCanvas, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(videoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblVideo))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVideo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(videoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblVideo;
    private java.awt.Canvas videoCanvas;
    private javax.swing.JPanel videoPanel;
    // End of variables declaration//GEN-END:variables
}
