package com.linkare.rec.acquisition;

/**
 * com/linkare/rec/acquisition/MaximumClientsReached.java . Generated by the
 * IDL-to-Java compiler (portable), version "3.1" from
 * I:/Projects/REC/IdlCompile/ReC7.idl Sexta-feira, 2 de Janeiro de 2004 15H12m
 * GMT
 */

public final class MaximumClientsReached extends org.omg.CORBA.UserException {
	public int errorCode = (int) 0;

	// Version 7.0 change
	public int maximumClients = (int) 0;

	public MaximumClientsReached() {
		super(MaximumClientsReachedHelper.id());
	} // ctor

	public MaximumClientsReached(int _errorCode, int _maximumClients) {
		super(MaximumClientsReachedHelper.id());
		errorCode = _errorCode;
		maximumClients = _maximumClients;
	} // ctor

	public MaximumClientsReached(String $reason, int _errorCode, int _maximumClients) {
		super(MaximumClientsReachedHelper.id() + "  " + $reason);
		errorCode = _errorCode;
		maximumClients = _maximumClients;
	} // ctor

} // class MaximumClientsReached
