package com.linkare.rec.acquisition;

/**
 * com/linkare/rec/acquisition/WrongConfigurationExceptionHolder.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.1" from
 * I:/Projects/REC/IdlCompile/ReC7.idl Sexta-feira, 2 de Janeiro de 2004 15H12m
 * GMT
 */

public final class WrongConfigurationExceptionHolder implements org.omg.CORBA.portable.Streamable {
	public com.linkare.rec.acquisition.WrongConfigurationException value = null;

	public WrongConfigurationExceptionHolder() {
	}

	public WrongConfigurationExceptionHolder(com.linkare.rec.acquisition.WrongConfigurationException initialValue) {
		value = initialValue;
	}

	public void _read(org.omg.CORBA.portable.InputStream i) {
		value = com.linkare.rec.acquisition.WrongConfigurationExceptionHelper.read(i);
	}

	public void _write(org.omg.CORBA.portable.OutputStream o) {
		com.linkare.rec.acquisition.WrongConfigurationExceptionHelper.write(o, value);
	}

	public org.omg.CORBA.TypeCode _type() {
		return com.linkare.rec.acquisition.WrongConfigurationExceptionHelper.type();
	}

}
