/*
 * ReCSplash.java
 *
 * Created on 01 July 2003, 00:18
 */

package com.linkare.rec.impl.baseUI;

/**
 *
 * @author  Jos� Pedro Pereira
 */

import java.util.logging.*;
import com.linkare.rec.impl.logging.*;
import com.linkare.rec.impl.utils.Defaults;
import com.linkare.rec.impl.i18n.ReCResourceBundle;
import com.linkare.rec.impl.baseUI.config.ReCBaseUIConfig;
import javax.swing.ImageIcon;

public class ReCSplash extends javax.swing.JDialog
{        
    private static String UI_CLIENT_LOGGER="ReC.baseUI";
    
    static
    {
	Logger l=LogManager.getLogManager().getLogger(UI_CLIENT_LOGGER);
	if(l==null)
	{
	    LogManager.getLogManager().addLogger(Logger.getLogger(UI_CLIENT_LOGGER));
	}
    }
    
    /** Creates new form ReCSplash */
    public ReCSplash()
    {
	this(null, false);
	initComponents();
        ReCBaseUIConfig recBaseUIConfig = ReCBaseUIConfig.sharedInstance();
        jLabelImage.setIcon(recBaseUIConfig.getSplashIcon());
    }
        
    /** Creates new form ReCSplash */
    public ReCSplash(java.awt.Frame parent, boolean modal)
    {
	super(parent, modal);
	initComponents();
        ReCBaseUIConfig recBaseUIConfig = ReCBaseUIConfig.sharedInstance();
        jLabelImage.setIcon(recBaseUIConfig.getSplashIcon());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents()//GEN-BEGIN:initComponents
    {
        jPanel1 = new javax.swing.JPanel();
        jLabelImage = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(ReCResourceBundle.findStringOrDefault("ReCBaseUI$rec.bui.status.loading.experiment", "Loading Experiment"));
        setBackground(java.awt.Color.white);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                closeDialog(evt);
            }
        });

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(new javax.swing.border.LineBorder(javax.swing.UIManager.getDefaults().getColor("Button.focus"), 1, true));
        jLabelImage.setBackground(java.awt.Color.white);
        jLabelImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImage.setOpaque(true);
        jPanel1.add(jLabelImage, java.awt.BorderLayout.CENTER);

        jProgressBar1.setBackground(new java.awt.Color(255, 255, 255));
        jProgressBar1.setForeground(javax.swing.UIManager.getDefaults().getColor("PasswordField.selectionBackground"));
        jProgressBar1.setMaximum(1000);
        jProgressBar1.setValue(5);
        jProgressBar1.setBorder(null);
        jProgressBar1.setBorderPainted(false);
        jProgressBar1.setIndeterminate(true);
        jProgressBar1.setString(ReCResourceBundle.findStringOrDefault("ReCBaseUI$rec.bui.status.loading.experiment", "Loading Experiment"));
        jProgressBar1.setStringPainted(true);
        jPanel1.add(jProgressBar1, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-410)/2, (screenSize.height-380)/2, 410, 380);
    }//GEN-END:initComponents
    
    /** Closes the dialog */
    public void closeDialog(java.awt.event.WindowEvent evt)
    {//GEN-FIRST:event_closeDialog
	setVisible(false);
	dispose();
    }//GEN-LAST:event_closeDialog

    /** Getter for property statusMessage.
     * @return Value of property statusMessage.
     */
    public String getStatusMessage()
    {
	return this.jProgressBar1.getString();
    }    
        
    /** Setter for property statusMessage.
     * @param statusMessage New value of property statusMessage.
     */
    public void setStatusMessage(String statusMessage)
    {
	this.jProgressBar1.setString(statusMessage);
    }    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
    
}
