version: '3'
services:
  client:
    build:
      context: client
    image: ${repo}/${simplifiedGroupId}/webswing-${webswing.version}-${openjdk.version}:${project.version}
  server:
    build:
      context: server
    image: ${repo}/${simplifiedGroupId}/payara-${payara.docker.version}:${project.version}
  multicast:
    build:
      context: multicast
    image: ${repo}/${simplifiedGroupId}/multicast:${project.version}