/*
 * TrafficLightPanel.java
 *
 * Created on July 22, 2004, 5:03 PM
 */

package com.linkare.rec.impl.baseUI.control;

/**
 *
 * @author André Neto - LEFT - IST
 */

import javax.swing.Icon;
import javax.swing.Timer;

import com.linkare.rec.impl.i18n.ReCResourceBundle;

public class TrafficLightPanel extends javax.swing.JPanel {
	/**
	 * 
	 */
	private static final long serialVersionUID = -7963654850508099730L;
	private Icon greenOn = null;
	private Icon greenOff = null;
	private Icon redOn = null;
	private Icon redOff = null;
	private Icon yellowOn = null;
	private Icon yellowOff = null;
	private final Icon yellowBlink = null;

	private final byte status = 0;
	public static final byte OFF = 0;
	public static final byte GREEN = 1;
	public static final byte YELLOW = 2;
	public static final byte RED = 3;
	public static final byte BLINK = 4;

	private Timer blinker = null;
	private boolean blinkON = false;

	/** Creates new form TrafficLightPanel */
	public TrafficLightPanel() {
		greenOn = ReCResourceBundle.findImageIconOrDefault(
				"ReCBaseUI$rec.bui.icon.trafficGreenOn",
				new javax.swing.ImageIcon(getClass().getResource(
						"/com/linkare/rec/impl/baseUI/resources/green_on_16.png")));
		greenOff = ReCResourceBundle.findImageIconOrDefault(
				"ReCBaseUI$rec.bui.icon.trafficGreenOff",
				new javax.swing.ImageIcon(getClass().getResource(
						"/com/linkare/rec/impl/baseUI/resources/green_off_16.png")));
		redOn = ReCResourceBundle.findImageIconOrDefault("ReCBaseUI$rec.bui.icon.trafficRedOn",
				new javax.swing.ImageIcon(getClass()
						.getResource("/com/linkare/rec/impl/baseUI/resources/red_on_16.png")));
		redOff = ReCResourceBundle.findImageIconOrDefault(
				"ReCBaseUI$rec.bui.icon.trafficRedOff",
				new javax.swing.ImageIcon(getClass().getResource(
						"/com/linkare/rec/impl/baseUI/resources/red_off_16.png")));
		yellowOn = ReCResourceBundle.findImageIconOrDefault(
				"ReCBaseUI$rec.bui.icon.trafficYellowOn",
				new javax.swing.ImageIcon(getClass().getResource(
						"/com/linkare/rec/impl/baseUI/resources/yellow_on_16.png")));
		yellowOff = ReCResourceBundle.findImageIconOrDefault(
				"ReCBaseUI$rec.bui.icon.trafficYellowOff",
				new javax.swing.ImageIcon(getClass().getResource(
						"/com/linkare/rec/impl/baseUI/resources/yellow_off_16.png")));
		// yellowBlink =
		// ReCResourceBundle.findImageIcon("ReCBaseUI$defaultTrafficYellowBlink",
		// new
		// javax.swing.ImageIcon("/com/linkare/rec/baseUI/resources/red_off_16.png"));

		initComponents();

		blinker = new Timer(500, new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(final java.awt.event.ActionEvent evt) {
				if (blinkON) {
					jLabelYellow.setIcon(yellowOff);
				} else {
					jLabelYellow.setIcon(yellowOn);
				}
				blinkON = !blinkON;
			}
		});
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents()// GEN-BEGIN:initComponents
	{
		jLabelGreen = new javax.swing.JLabel();
		jLabelYellow = new javax.swing.JLabel();
		jLabelRed = new javax.swing.JLabel();

		setLayout(new java.awt.GridLayout(1, 3, 2, 0));

		jLabelGreen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelGreen.setIcon(greenOff);
		add(jLabelGreen);

		jLabelYellow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelYellow.setIcon(yellowOff);
		add(jLabelYellow);

		jLabelRed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelRed.setIcon(redOff);
		add(jLabelRed);

	}// GEN-END:initComponents

	public void changeTrafficStatus(final byte status) {
		if (blinker.isRunning()) {
			blinker.stop();
		}

		if (status == TrafficLightPanel.OFF) {
			jLabelGreen.setIcon(greenOff);
			jLabelYellow.setIcon(yellowOff);
			jLabelRed.setIcon(redOff);
		} else if (status == TrafficLightPanel.GREEN) {
			jLabelGreen.setIcon(greenOn);
			jLabelYellow.setIcon(yellowOff);
			jLabelRed.setIcon(redOff);
		} else if (status == TrafficLightPanel.YELLOW) {
			jLabelGreen.setIcon(greenOff);
			jLabelYellow.setIcon(yellowOn);
			jLabelRed.setIcon(redOff);
		} else if (status == TrafficLightPanel.RED) {
			jLabelGreen.setIcon(greenOff);
			jLabelYellow.setIcon(yellowOff);
			jLabelRed.setIcon(redOn);
		} else if (status == TrafficLightPanel.BLINK) {
			jLabelGreen.setIcon(greenOff);
			jLabelRed.setIcon(redOff);
			blinker.start();
		}
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel jLabelGreen;
	private javax.swing.JLabel jLabelRed;
	private javax.swing.JLabel jLabelYellow;
	// End of variables declaration//GEN-END:variables

}
