/*
 * Ivo.java
 *
 * Created on December 13, 2004, 3:33 PM
 */

package test;

/**
 *
 * @author André Neto - LEFT - IST
 */

import pt.utl.ist.elab.client.serial.stamp.thomson.displays.*;

import java.awt.*;
import java.awt.image.*;
import javax.swing.border.*;

public class Ivo extends javax.swing.JFrame
{
    Image[] images = null;
    
    
    /** Creates new form Ivo */
    public Ivo()
{
        initComponents();
        try
        {
            java.awt.Image image = new javax.swing.ImageIcon(getClass().getResource("/test/ivo.jpg")).getImage();//  javax.imageio.ImageIO.read(new java.io.File("/home/andre/ivo.jpg"));
            AnalizadorImagens analisador = new AnalizadorImagens();
            images = analisador.getImagemAlinhada(image);
            double[] xyr = analisador.getCircunferenciaPontos(images[3]);
            images[4] = analisador.getFinalimage(images[2]);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        if(images != null && images.length > 0)
        {
            paintImage(images[0]);
            jPanel1.setPreferredSize(new Dimension(images[0].getWidth(null), images[0].getHeight(null)));
            pack();
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents()//GEN-BEGIN:initComponents
    {
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton0 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                exitForm(evt);
            }
        });

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jButton0.setText("0");
        jButton0.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton0ActionPerformed(evt);
            }
        });

        jPanel2.add(jButton0);

        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.add(jButton1);

        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel2.add(jButton2);

        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel2.add(jButton3);

        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton4ActionPerformed(evt);
            }
        });

        jPanel2.add(jButton4);

        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton5ActionPerformed(evt);
            }
        });

        jPanel2.add(jButton5);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }//GEN-END:initComponents
    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton5ActionPerformed
    {//GEN-HEADEREND:event_jButton5ActionPerformed
        
        if(images != null && images.length > 5)            
            paintImage(images[5]);                
    }//GEN-LAST:event_jButton5ActionPerformed
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton4ActionPerformed
    {//GEN-HEADEREND:event_jButton4ActionPerformed
        if(images != null && images.length > 4)
            paintImage(images[4]);                
    }//GEN-LAST:event_jButton4ActionPerformed
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton3ActionPerformed
    {//GEN-HEADEREND:event_jButton3ActionPerformed
        if(images != null && images.length > 3)
            paintImage(images[3]);                
    }//GEN-LAST:event_jButton3ActionPerformed
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        if(images != null && images.length > 2)
            paintImage(images[2]);                
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        if(images != null && images.length > 1)
            paintImage(images[1]);                
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton0ActionPerformed
    {//GEN-HEADEREND:event_jButton0ActionPerformed
        if(images != null && images.length > 0)
            paintImage(images[0]);                
    }//GEN-LAST:event_jButton0ActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt)//GEN-FIRST:event_exitForm
    {
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        new Ivo().show();
    }
    
    
    private void paintImage(java.awt.Image img)
    {
        jPanel1.setBorder(new ImageBorder(img, false));
    }
    
    public class ImageBorder implements Border
    {
        private Image image;
        
        /** Creates a new instance of ImageBorder */
        public ImageBorder(Image image, boolean fill)
        {
            this.image = image;
            this.fill = fill;
        }
        
        
        public void paintBorder(Component c, Graphics g, int x, int y, int width, int height)
        {
            if(image == null)
            {
                return;
            }
            if(!fill)
            {
                int x0 = x + (width-image.getWidth(null))/2;
                int y0 = y + (height-image.getHeight(null))/2;
                g.drawImage(image, x0, y0, null);
            }
            else
            {
                g.drawImage(image, 0, 0, width, height,  null);
            }
        }
        
        public Insets getBorderInsets(Component c)
        {
            return new Insets(0,0,0,0);
        }
        
        public boolean isBorderOpaque()
        {
            return true;
        }
        
        private boolean fill = true;
        public void setFill(boolean fill)
        {
            this.fill = fill;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
    
}
