/*
 * SimpleLoginBox.java created on Apr 16, 2009
 *
 * Copyright 2009 HFernandes. All rights reserved.
 * HFernandes PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */

package com.linkare.rec.impl.newface.component;

import java.awt.Color;

import javax.swing.Icon;

import org.jdesktop.application.Action;

import com.linkare.rec.impl.newface.ReCApplication;
import com.linkare.rec.impl.newface.component.ProgressCicle.State;
import com.linkare.rec.impl.newface.config.Lab;
import com.linkare.rec.impl.newface.utils.LAFConnector;
import com.linkare.rec.impl.newface.utils.LAFConnector.SpecialELabProperties;

/**
 * 
 * @author npadriano
 */
public class LabLoginBox extends GradientPane {

	/** Generated UID */
	private static final long serialVersionUID = -918799173616242126L;
	
	private ReCApplication recApplication = ReCApplication.getApplication();

	/** Creates new form SimpleLoginBox */
	public LabLoginBox() {
		super();
		setContainer(container);
		initComponents();
		txtUsername.setText(System.getProperty("user.name"));
	}

	public void setLoginProgressVisible(boolean visible) {
		progressCicle.setVisible(visible);
		progressCicle.setState(visible ? State.RUNNING : State.IDLE);
	}

	public void setIdleIcon(Icon idleIcon) {
		this.progressCicle.setIdleIcon(idleIcon);
	}

	public void setBusyIcons(Icon[] busyIcons) {
		this.progressCicle.setBusyIcons(busyIcons);
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
	 * content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        progressCicle = new com.linkare.rec.impl.newface.component.ProgressCicle();
        btnGo = new com.linkare.rec.impl.newface.component.FlatButton();
        labelPassword = new javax.swing.JLabel();
        labCombo = new javax.swing.JComboBox();
        labelPassword1 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnQuit = new com.linkare.rec.impl.newface.component.FlatButton();

        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(360, 280));

        labelUsername.setFont(labelUsername.getFont().deriveFont(labelUsername.getFont().getStyle() | java.awt.Font.BOLD));
        labelUsername.setForeground(LAFConnector.getColor(SpecialELabProperties.SELECTION_FOREGROUND_ON_DARK));
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.linkare.rec.impl.newface.ReCApplication.class).getContext().getResourceMap(LabLoginBox.class);
        labelUsername.setText(resourceMap.getString("labelUsername.text")); // NOI18N
        labelUsername.setName("labelUsername"); // NOI18N

        txtUsername.setText(resourceMap.getString("txtUsername.text")); // NOI18N
        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(com.linkare.rec.impl.newface.ReCApplication.class).getContext().getActionMap(LabLoginBox.class, this);
        txtUsername.setAction(actionMap.get("next")); // NOI18N
        txtUsername.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(Color.BLACK), javax.swing.BorderFactory.createEmptyBorder(2, 3, 2, 3)));
        txtUsername.setName("txtUsername"); // NOI18N
        txtUsername.setPreferredSize(new java.awt.Dimension(215, 28));

        progressCicle.setText(resourceMap.getString("progressCicle.text")); // NOI18N
        progressCicle.setIdleIcon(resourceMap.getIcon("progressCicle.idleIcon")); // NOI18N
        progressCicle.setName("progressCicle"); // NOI18N

        btnGo.setAction(actionMap.get("next")); // NOI18N
        btnGo.setFont(btnGo.getFont().deriveFont(btnGo.getFont().getStyle() | java.awt.Font.BOLD));
        btnGo.setName("btnGo"); // NOI18N

        labelPassword.setFont(labelPassword.getFont().deriveFont(labelPassword.getFont().getStyle() | java.awt.Font.BOLD));
        labelPassword.setForeground(LAFConnector.getColor(SpecialELabProperties.SELECTION_FOREGROUND_ON_DARK));
        labelPassword.setText(resourceMap.getString("labelPassword.text")); // NOI18N
        labelPassword.setName("labelPassword"); // NOI18N

        labCombo.setModel(getRecApplication().getLabComboBoxModel());
        labCombo.setName("labCombo"); // NOI18N
        labCombo.setRenderer(new com.linkare.rec.impl.newface.component.LabRenderer());

        labelPassword1.setFont(labelPassword1.getFont().deriveFont(labelPassword1.getFont().getStyle() | java.awt.Font.BOLD));
        labelPassword1.setForeground(LAFConnector.getColor(SpecialELabProperties.SELECTION_FOREGROUND_ON_DARK));
        labelPassword1.setText(resourceMap.getString("labelPassword1.text")); // NOI18N
        labelPassword1.setName("labelPassword1"); // NOI18N

        txtPassword.setText(resourceMap.getString("txtPassword.text")); // NOI18N
        txtPassword.setAction(actionMap.get("next")); // NOI18N
        txtPassword.setName("txtPassword"); // NOI18N

        btnQuit.setAction(actionMap.get("quit")); // NOI18N
        btnQuit.setForeground(resourceMap.getColor("btnQuit.foreground")); // NOI18N
        btnQuit.setText(resourceMap.getString("btnQuit.text")); // NOI18N
        btnQuit.setToolTipText(resourceMap.getString("btnQuit.toolTipText")); // NOI18N
        btnQuit.setBorderColor(resourceMap.getColor("btnQuit.borderColor")); // NOI18N
        btnQuit.setFont(btnQuit.getFont().deriveFont(btnQuit.getFont().getStyle() | java.awt.Font.BOLD));
        btnQuit.setGradientBottom(resourceMap.getColor("btnQuit.gradientBottom")); // NOI18N
        btnQuit.setGradientTop(resourceMap.getColor("btnQuit.gradientTop")); // NOI18N
        btnQuit.setName("btnQuit"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPassword1)
                    .addComponent(labelPassword)
                    .addComponent(labelUsername)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnGo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnQuit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(progressCicle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(labelUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelPassword)
                .addGap(7, 7, 7)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(labelPassword1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(progressCicle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnQuit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(47, 47, 47))))
        );
    }// </editor-fold>//GEN-END:initComponents

	@Action
	public void next() {
		setLoginProgressVisible(true);

		recApplication.setUserInfo(getUsername(), getPassword());
		
		// set lab with selected from lab combo
		Lab lab = (Lab) labCombo.getSelectedItem();
		recApplication.setCurrentLab(lab);

		// Connect
		recApplication.connect();
	}

	public String getUsername() {
		return txtUsername.getText();
	}

	public String getPassword() {
		return new String(txtPassword.getPassword());
	}
	
	public void reset() {
		if (labCombo.getModel().getSize() > 0) {
			labCombo.setSelectedIndex(0);
		}
		txtPassword.setText("");
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.linkare.rec.impl.newface.component.FlatButton btnGo;
    private com.linkare.rec.impl.newface.component.FlatButton btnQuit;
    private javax.swing.JComboBox labCombo;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelPassword1;
    private javax.swing.JLabel labelUsername;
    private com.linkare.rec.impl.newface.component.ProgressCicle progressCicle;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

}
