package com.linkare.rec.acquisition;

/**
 * com/linkare/rec/acquisition/DataProducerHelper.java . Generated by the
 * IDL-to-Java compiler (portable), version "3.1" from
 * I:/Projects/REC/IdlCompile/ReC7.idl Sexta-feira, 2 de Janeiro de 2004 15H12m
 * GMT
 */

// ok, not known at this time
public abstract class DataProducerHelper {
	private static String _id = "IDL:com/linkare/rec/acquisition/DataProducer:1.0";

	public static void insert(final org.omg.CORBA.Any a, final com.linkare.rec.acquisition.DataProducer that) {
		final org.omg.CORBA.portable.OutputStream out = a.create_output_stream();
		a.type(DataProducerHelper.type());
		DataProducerHelper.write(out, that);
		a.read_value(out.create_input_stream(), DataProducerHelper.type());
	}

	public static com.linkare.rec.acquisition.DataProducer extract(final org.omg.CORBA.Any a) {
		return DataProducerHelper.read(a.create_input_stream());
	}

	private static org.omg.CORBA.TypeCode __typeCode = null;

	synchronized public static org.omg.CORBA.TypeCode type() {
		if (DataProducerHelper.__typeCode == null) {
			DataProducerHelper.__typeCode = org.omg.CORBA.ORB.init().create_interface_tc(
					com.linkare.rec.acquisition.DataProducerHelper.id(), "DataProducer");
		}
		return DataProducerHelper.__typeCode;
	}

	public static String id() {
		return DataProducerHelper._id;
	}

	public static com.linkare.rec.acquisition.DataProducer read(final org.omg.CORBA.portable.InputStream istream) {
		return DataProducerHelper.narrow(istream.read_Object(_DataProducerStub.class));
	}

	public static void write(final org.omg.CORBA.portable.OutputStream ostream,
			final com.linkare.rec.acquisition.DataProducer value) {
		ostream.write_Object(value);
	}

	public static com.linkare.rec.acquisition.DataProducer narrow(final org.omg.CORBA.Object obj) {
		if (obj == null) {
			return null;
		} else if (obj instanceof com.linkare.rec.acquisition.DataProducer) {
			return (com.linkare.rec.acquisition.DataProducer) obj;
		} else if (!obj._is_a(DataProducerHelper.id())) {
			throw new org.omg.CORBA.BAD_PARAM();
		} else {
			final org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate();
			final com.linkare.rec.acquisition._DataProducerStub stub = new com.linkare.rec.acquisition._DataProducerStub();
			stub._set_delegate(delegate);
			return stub;
		}
	}

}
