package com.linkare.rec.acquisition;

/**
 * com/linkare/rec/acquisition/UserInfoListHolder.java . Generated by the
 * IDL-to-Java compiler (portable), version "3.1" from
 * I:/Projects/REC/IdlCompile/ReC7.idl Sabado, 17 de Janeiro de 2004 19H00m GMT
 */

// Version 7.0 Addition
public final class UserInfoListHolder implements org.omg.CORBA.portable.Streamable {
	public com.linkare.rec.acquisition.UserInfo value[] = null;

	public UserInfoListHolder() {
	}

	public UserInfoListHolder(final com.linkare.rec.acquisition.UserInfo[] initialValue) {
		value = initialValue;
	}

	@Override
	public void _read(final org.omg.CORBA.portable.InputStream i) {
		value = com.linkare.rec.acquisition.UserInfoListHelper.read(i);
	}

	@Override
	public void _write(final org.omg.CORBA.portable.OutputStream o) {
		com.linkare.rec.acquisition.UserInfoListHelper.write(o, value);
	}

	@Override
	public org.omg.CORBA.TypeCode _type() {
		return com.linkare.rec.acquisition.UserInfoListHelper.type();
	}

}
