/*
 * ApparatusTabbedPane.java created on May 20, 2009
 *
 * Copyright 2009 HFernandes. All rights reserved.
 * HFernandes PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */

package com.linkare.rec.impl.newface.component;

import java.util.List;
import java.util.logging.Logger;

import javax.swing.JPanel;
import javax.swing.JToolBar;

import com.linkare.rec.impl.client.experiment.ExpDataDisplay;
import com.linkare.rec.impl.newface.ReCApplication.ExperimentUIData;

/**
 * 
 * @author hfernandes
 */
public class ApparatusTabbedHistoryPane extends GradientPane {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3456817251741825019L;

	@SuppressWarnings("unused")
	private static final Logger log = Logger.getLogger(ApparatusTabbedHistoryPane.class.getName());

	public static final int TAB_DESCRIPTION = 0;

	public static final int TAB_RESULTS = 1;

	/** Creates new form ApparatusTabbedPane 
	 * @param experimentUIData */
	public ApparatusTabbedHistoryPane(final ExperimentUIData experimentUIData) {
		initComponents();
		resultsActionBar.setPlayStopButtonVisible(false);

		setDataDisplays(experimentUIData.getDataDisplays());
	}

	public ApparatusDescriptionPane getDescriptionPane() {
		return descriptionPane;
	}

	public JPanel getResultsHolderPane() {
		return resultsHolderPane;
	}

	public void setSelectedTabIndex(final int index) {
		tabbedPane.setSelectedIndex(index);
	}

	public void setTabIndexEnabled(final int index, final boolean enabled) {
		tabbedPane.setEnabledAt(index, enabled);
	}

	private void setDataDisplays(final List<ExpDataDisplay> displays) {
		for (final ExpDataDisplay display : displays) {
			if (display.getToolBar() != null) {
				final JToolBar toolBar = display.getToolBar();
				toolBar.getComponent(0).setEnabled(false);
				toolBar.setName("toolBar");
				toolBar.setOpaque(false);
				toolBar.setMinimumSize(resultsActionBar.getMinimumSize());
				resultsHolderPane.remove(resultsActionBar);
				resultsHolderPane.add(toolBar, java.awt.BorderLayout.PAGE_END);
				revalidate();
				repaint();
			}
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		tabbedPane = new javax.swing.JTabbedPane();
		descriptionPane = new com.linkare.rec.impl.newface.component.ApparatusDescriptionPane();
		resultsHolderPane = new javax.swing.JPanel();
		resultsActionBar = new com.linkare.rec.impl.newface.component.ResultsActionBar();

		setName("Form"); // NOI18N
		setOpaque(false);
		setLayout(new java.awt.BorderLayout());

		tabbedPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 6, 6, 6));
		tabbedPane.setName("tabbedPane"); // NOI18N

		final org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application
				.getInstance(com.linkare.rec.impl.newface.ReCApplication.class).getContext()
				.getResourceMap(ApparatusTabbedHistoryPane.class);
		descriptionPane.setBackground(resourceMap.getColor("descriptionPane.background")); // NOI18N
		descriptionPane.setName("descriptionPane"); // NOI18N
		descriptionPane.setOpaque(false);
		tabbedPane.addTab(resourceMap.getString("descriptionPane.TabConstraints.tabTitle"),
				resourceMap.getIcon("descriptionPane.TabConstraints.tabIcon"), descriptionPane); // NOI18N

		resultsHolderPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 6, 6, 6));
		resultsHolderPane.setName("resultsHolderPane"); // NOI18N
		resultsHolderPane.setLayout(new java.awt.BorderLayout());

		resultsActionBar.setName("resultsActionBar"); // NOI18N
		resultsHolderPane.add(resultsActionBar, java.awt.BorderLayout.PAGE_END);

		tabbedPane.addTab(resourceMap.getString("resultsHolderPane.TabConstraints.tabTitle"), resultsHolderPane); // NOI18N

		add(tabbedPane, java.awt.BorderLayout.CENTER);
	}// </editor-fold>//GEN-END:initComponents

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private com.linkare.rec.impl.newface.component.ApparatusDescriptionPane descriptionPane;
	private com.linkare.rec.impl.newface.component.ResultsActionBar resultsActionBar;
	private javax.swing.JPanel resultsHolderPane;
	private javax.swing.JTabbedPane tabbedPane;
	// End of variables declaration//GEN-END:variables

}
