package com.linkare.rec.impl.newface.component;

import static uk.co.caprica.vlcj.javafx.videosurface.ImageViewVideoSurfaceFactory.videoSurfaceForImageView;

import java.awt.BorderLayout;

import javax.swing.JDialog;

import com.linkare.rec.impl.newface.ReCApplication;
import com.linkare.rec.impl.newface.component.media.MediaSetup;

import javafx.application.Platform;
import javafx.embed.swing.JFXPanel;
import javafx.scene.Scene;
import javafx.scene.image.ImageView;
import javafx.scene.layout.BorderPane;
import javafx.stage.Stage;
import uk.co.caprica.vlcj.factory.MediaPlayerFactory;
import uk.co.caprica.vlcj.player.base.MediaPlayer;
import uk.co.caprica.vlcj.player.base.MediaPlayerEventAdapter;
import uk.co.caprica.vlcj.player.embedded.EmbeddedMediaPlayer;

/**
 * 
 * @author pmatrola
 */
public class VideoContentDialogPanel extends AbstractContentPane {

	private static final long serialVersionUID = -865357167158613899L;

	private JDialog dialog;
	private static Stage stage;
	private static ImageView videoImageView;
	private static MediaPlayerFactory mediaPlayerFactory;
	private static EmbeddedMediaPlayer player;
	
	/**
	 * Creates new form VideoContentDialogPanel
	 * 
	 * @param dialog
	 */
	public VideoContentDialogPanel(JDialog dialog, String mrl) {
		this.dialog = dialog;
		initComponents(mrl);
	}

	private static void initFX(JFXPanel fxPanel, String mrl) {
        stage = new Stage();  
        
        stage.setTitle("Hello Java FX");  
        stage.setResizable(true);  

        BorderPane root = new BorderPane();
        root.setStyle("-fx-background-color: transparent;");

        videoImageView.fitWidthProperty().bind(root.widthProperty());
        videoImageView.fitHeightProperty().bind(root.heightProperty());

        root.widthProperty().addListener((observableValue, oldValue, newValue) -> {
            // If you need to know about resizes
        });

        root.heightProperty().addListener((observableValue, oldValue, newValue) -> {
            // If you need to know about resizes
        });

        root.setCenter(videoImageView);
        
        Scene scene = new Scene(root,80,20);  
        stage.setScene(scene);                   
         
        fxPanel.setScene(scene);
        fxPanel.setVisible(true);
        
        player.media().play(mrl);
	}
	
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents(String mrl) {
		Platform.setImplicitExit(false);
		final JFXPanel fxPanel = new JFXPanel();
		
		// mediaPlayerFactory = new MediaPlayerFactory(getDefaultEmbeddedMediaParameters());
		// FullScreenStrategy fullScreenStrategy = new ExclusiveModeFullScreenStrategy(window);
		// player.fullScreen().strategy(fullScreenStrategy);
		// player.controls().setRate(1.f);

        mediaPlayerFactory = new MediaPlayerFactory(MediaSetup.getDefaultEmbeddedMediaParameters());
        player = mediaPlayerFactory.mediaPlayers().newEmbeddedMediaPlayer();
        player.events().addMediaPlayerEventListener(new MediaPlayerEventAdapter() {
            @Override
            public void playing(MediaPlayer mediaPlayer) {
            }

            @Override
            public void paused(MediaPlayer mediaPlayer) {
            }

            @Override
            public void stopped(MediaPlayer mediaPlayer) {
            }

            @Override
            public void timeChanged(MediaPlayer mediaPlayer, long newTime) {
            }
        });
        
        videoImageView = new ImageView();
        videoImageView.setPreserveRatio(true);

        player.videoSurface().set(videoSurfaceForImageView(videoImageView));
		//window.getContentPane().add(fxPanel);
        //window.setSize(100,100);
        fxPanel.setEnabled(true);
		fxPanel.setSize(100,100);
        
		setLayout(new BorderLayout());
		setSize(50,50);
		add(fxPanel);
	    setVisible(true);
		//mediaPanel.repaint();
		
	    dialog.setVisible(true);
	    dialog.setResizable(true);
	    Platform.runLater(new Runnable() {
	        @Override public void run() {
	          initFX(fxPanel, mrl);        
	        }
	      });
		
	}// </editor-fold>//GEN-END:initComponents

	public void closeWindow() {
		if (player != null) {
			player.release();
		}
		if (dialog != null) {
			dialog.dispose();
		} else {
			this.setVisible(false);
		}
	}
}