/*
 * JAcquisitionHeaderDisplay.java
 *
 * Created on 9 de Maio de 2003, 12:12
 */

package com.linkare.rec.impl.baseUI;

import java.awt.Graphics;

import javax.swing.JComponent;

import com.linkare.rec.data.config.HardwareAcquisitionConfig;
import com.linkare.rec.impl.i18n.ReCResourceBundle;

/**
 * 
 * @author José Pedro Pereira - Linkare TI
 */
public class JAcquisitionHeaderDisplay extends javax.swing.JPanel implements AcquisitionHeaderDisplay {
	private static final String NO_HEADER_STR = ReCResourceBundle.findStringOrDefault(
			"ReCBaseUI$rec.bui.lbl.noHeaderStatus", "No header yet!");

	/** Holds value of property acquisitionHeader. */
	private HardwareAcquisitionConfig acquisitionHeader;

	/** Creates new form JAcquisitionHeaderDisplay */
	public JAcquisitionHeaderDisplay() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents()// GEN-BEGIN:initComponents
	{
		textPaneHeader = new javax.swing.JTextPane();

		setLayout(new java.awt.BorderLayout());

		textPaneHeader.setEditable(false);
		textPaneHeader.setText(NO_HEADER_STR);
		add(textPaneHeader, java.awt.BorderLayout.CENTER);

	}// GEN-END:initComponents

	/**
	 * Getter for property acquisitionHeader.
	 * 
	 * @return Value of property acquisitionHeader.
	 */
	public HardwareAcquisitionConfig getAcquisitionHeader() {
		return this.acquisitionHeader;
	}

	/**
	 * Setter for property acquisitionHeader.
	 * 
	 * @param acquisitionHeader New value of property acquisitionHeader.
	 */
	public void setAcquisitionHeader(HardwareAcquisitionConfig acquisitionHeader) {
		this.acquisitionHeader = acquisitionHeader;
		if (acquisitionHeader != null)
			textPaneHeader.setText(acquisitionHeader.toString());
		else
			textPaneHeader.setText(NO_HEADER_STR);

		repaint();
	}

	public JComponent getDisplayComponent() {
		return this;
	}

	/**
	 * Getter for property text.
	 * 
	 * @return Value of property text.
	 */
	public String getText() {
		return this.textPaneHeader.getText();
	}

	public void print(Graphics g) {
		textPaneHeader.print(g);
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JTextPane textPaneHeader;
	// End of variables declaration//GEN-END:variables

}
