/*
 * Laffy - Swing Look and Feel Sampler
 * Copyright (C) Sun Microsystems
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA
 */

package org.jdesktop.laffy.combospinner;

import org.jdesktop.laffy.I18nResourceHandler;
import org.jdesktop.laffy.OptionsSettablePanel;

import javax.swing.JButton;
import javax.swing.JComboBox;
import java.awt.Color;
import java.awt.Component;

/** @author Jasper Potts */
public class EditableComboPanel extends OptionsSettablePanel {

    private final Color DEFAULT_BACKGROUND;
    private final boolean DEFAULT_OPAQUE;

    /** Creates new form ComboPanel */
    public EditableComboPanel() {
        initComponents();
        DEFAULT_BACKGROUND = jComboBox1.getBackground();
        DEFAULT_OPAQUE = jComboBox1.isOpaque();

        setArrowButtonState(jComboBox2, I18nResourceHandler.getMessage("MouseOver"));
        setArrowButtonState(jComboBox5, I18nResourceHandler.getMessage("MouseOver"));
        setArrowButtonState(jComboBox3, I18nResourceHandler.getMessage("Pressed"));
        setArrowButtonState(jComboBox6, I18nResourceHandler.getMessage("Pressed"));
    }

    private static final void setArrowButtonState(JComboBox combo, String value) {
        for (Component component : combo.getComponents()) {
            if (component instanceof JButton) {
                ((JButton) component).putClientProperty("Nimbus.State", value);
            }
        }
    }

    // =================================================================================================================
    // OptionsSettablePanel Methods

    @Override public void setForceComponentsBackgroundColor(boolean force) {
        System.out.println("ButtonPanel.setForceComponetsbackgroundRed " + force);
        Color c = force ? FORCED_BACKGROUND : DEFAULT_BACKGROUND;
//        boolean o = force ? true : DEFAULT_OPAQUE;
        jComboBox1.setBackground(c);
        jComboBox16.setBackground(c);
        jComboBox2.setBackground(c);
        jComboBox3.setBackground(c);
        jComboBox4.setBackground(c);
        jComboBox5.setBackground(c);
        jComboBox6.setBackground(c);
//        jComboBox1.setOpaque(o);
//        jComboBox16.setOpaque(o);
//        jComboBox2.setOpaque(o);
//        jComboBox3.setOpaque(o);
//        jComboBox4.setOpaque(o);
//        jComboBox5.setOpaque(o);
//        jComboBox6.setOpaque(o);
    }

    @Override public void setForceComponentsNonOpaque(boolean force) {
        setBackground(force ? Color.GREEN : DEFAULT_BACKGROUND);
        boolean o = force ? false : DEFAULT_OPAQUE;
        jComboBox1.setOpaque(o);
        jComboBox16.setOpaque(o);
        jComboBox2.setOpaque(o);
        jComboBox3.setOpaque(o);
        jComboBox4.setOpaque(o);
        jComboBox5.setOpaque(o);
        jComboBox6.setOpaque(o);
    }

    // =================================================================================================================
    // Netbeans Code

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jComboBox5 = new JComboBox(){
            public boolean hasFocus(){
                return true;
            }
        };
        jComboBox6 = new JComboBox(){
            public boolean hasFocus(){
                return true;
            }
        };
        jComboBox16 = new JComboBox(){
            public boolean hasFocus(){
                return true;
            }
        };

        setLayout(new java.awt.GridBagLayout());

        jLabel8.setFont(jLabel8.getFont().deriveFont(jLabel8.getFont().getStyle() | java.awt.Font.BOLD, jLabel8.getFont().getSize()-2));
        jLabel8.setForeground(java.awt.Color.darkGray);
        //jLabel8.setText("Normal");
        jLabel8.setText(I18nResourceHandler.getMessage("Normal"));
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 2, 5);
        add(jLabel8, gridBagConstraints);

        jLabel2.setFont(jLabel2.getFont().deriveFont(jLabel2.getFont().getStyle() | java.awt.Font.BOLD, jLabel2.getFont().getSize()-2));
        jLabel2.setForeground(java.awt.Color.darkGray);
        //jLabel2.setText("Focused");
        jLabel2.setText(I18nResourceHandler.getMessage("Focused"));
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 2, 5);
        add(jLabel2, gridBagConstraints);

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD, jLabel1.getFont().getSize()-2));
        jLabel1.setForeground(java.awt.Color.darkGray);
        //jLabel1.setText("Normal");
        jLabel1.setText(I18nResourceHandler.getMessage("Normal"));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(4, 2, 4, 2);
        add(jLabel1, gridBagConstraints);

        jLabel5.setFont(jLabel5.getFont().deriveFont(jLabel5.getFont().getStyle() | java.awt.Font.BOLD, jLabel5.getFont().getSize()-2));
        jLabel5.setForeground(java.awt.Color.darkGray);
        //jLabel5.setText("Over");
        jLabel5.setText(I18nResourceHandler.getMessage("Over"));
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(4, 2, 4, 2);
        add(jLabel5, gridBagConstraints);

        jLabel7.setFont(jLabel7.getFont().deriveFont(jLabel7.getFont().getStyle() | java.awt.Font.BOLD, jLabel7.getFont().getSize()-2));
        jLabel7.setForeground(java.awt.Color.darkGray);
        //jLabel7.setText("Pressed");
        jLabel7.setText(I18nResourceHandler.getMessage("Pressed"));
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(4, 2, 4, 2);
        add(jLabel7, gridBagConstraints);

        jLabel6.setFont(jLabel6.getFont().deriveFont(jLabel6.getFont().getStyle() | java.awt.Font.BOLD, jLabel6.getFont().getSize()-2));
        jLabel6.setForeground(java.awt.Color.darkGray);
        //jLabel6.setText("Disabled");
        jLabel6.setText(I18nResourceHandler.getMessage("Disabled"));
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(4, 2, 4, 2);
        add(jLabel6, gridBagConstraints);

        jComboBox1.setEditable(true);
        //jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Item 1", "Item 2", "Item 3", "Item 4"}));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { I18nResourceHandler.getMessage("Item_1"), I18nResourceHandler.getMessage("Item_2"), I18nResourceHandler.getMessage("Item_3"), I18nResourceHandler.getMessage("Item_4") }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        add(jComboBox1, gridBagConstraints);

        jComboBox2.setEditable(true);
        //jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Item 1", "Item 2", "Item 3", "Item 4"}));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { I18nResourceHandler.getMessage("Item_1"), I18nResourceHandler.getMessage("Item_2"), I18nResourceHandler.getMessage("Item_3"), I18nResourceHandler.getMessage("Item_4") }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        add(jComboBox2, gridBagConstraints);

        jComboBox3.setEditable(true);
        //jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Item 1", "Item 2", "Item 3", "Item 4"}));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { I18nResourceHandler.getMessage("Item_1"), I18nResourceHandler.getMessage("Item_2"), I18nResourceHandler.getMessage("Item_3"), I18nResourceHandler.getMessage("Item_4") }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        add(jComboBox3, gridBagConstraints);

        jComboBox4.setEditable(true);
        //jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Item 1", "Item 2", "Item 3", "Item 4"}));
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { I18nResourceHandler.getMessage("Item_1"), I18nResourceHandler.getMessage("Item_2"), I18nResourceHandler.getMessage("Item_3"), I18nResourceHandler.getMessage("Item_4") }));
        jComboBox4.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        add(jComboBox4, gridBagConstraints);

        jComboBox5.setEditable(true);
        //jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Item 1", "Item 2", "Item 3", "Item 4"}));
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { I18nResourceHandler.getMessage("Item_1"), I18nResourceHandler.getMessage("Item_2"), I18nResourceHandler.getMessage("Item_3"), I18nResourceHandler.getMessage("Item_4") }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        add(jComboBox5, gridBagConstraints);

        jComboBox6.setEditable(true);
        //jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Item 1", "Item 2", "Item 3", "Item 4"}));
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { I18nResourceHandler.getMessage("Item_1"), I18nResourceHandler.getMessage("Item_2"), I18nResourceHandler.getMessage("Item_3"), I18nResourceHandler.getMessage("Item_4") }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        add(jComboBox6, gridBagConstraints);

        jComboBox16.setEditable(true);
        //jComboBox16.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Item 1", "Item 2", "Item 3", "Item 4"}));
        jComboBox16.setModel(new javax.swing.DefaultComboBoxModel(new String[] { I18nResourceHandler.getMessage("Item_1"), I18nResourceHandler.getMessage("Item_2"), I18nResourceHandler.getMessage("Item_3"), I18nResourceHandler.getMessage("Item_4") }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        add(jComboBox16, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox16;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables

}
