/*
 * LoginBox.java created on Mar 10, 2009
 *
 * Copyright 2009 HFernandes. All rights reserved.
 * HFernandes PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */

package com.linkare.rec.impl.newface.component;

import java.awt.Color;
import java.util.logging.Logger;

import javax.swing.JPasswordField;
import javax.swing.UIManager;

/**
 *
 * @author hfernandes
 */
public class LoginBox extends GradientPane {

    private static final long serialVersionUID = 698114786085470559L;
    
    @SuppressWarnings("unused")
	private static final Logger log = Logger.getLogger(LoginBox.class.getName());
    
    /**
	 * The LOGIN action identifier.
	 */
	public static final String ACTION_DO_LOGIN = LoginBox.class.getSimpleName() + "_ACTION_LOGIN";
	
	/** Creates new form LoginBox */
	public LoginBox() {
		super(GradientStyle.VERTICAL_LINEAR_DARK_TO_LIGHT);

		initComponents();
		customInit();
	}

	private void customInit() {
		Color fgColor = UIManager.getColor(SpecialLAFProperties.ENABLED_FOREGROUND_ON_DARK.getName());
		if (fgColor != null) {
			lblUserName.setForeground(fgColor);
			lblPassword.setForeground(fgColor);
		}
	}
	
	/**
	 * @return the username
	 */
	public String getUsername() {
		return txtUsername.getText();
	}
	
	/**
	 * @see JPasswordField#getPassword()
	 * @return the password text
	 */
	public String getPassword() {
		return new String(passField.getPassword());
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblUserName = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        passField = new javax.swing.JPasswordField();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        setPreferredSize(new java.awt.Dimension(360, 194));
        setLayout(new java.awt.GridBagLayout());

        lblUserName.setText("Nome de Utilizador");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 2, 0);
        add(lblUserName, gridBagConstraints);

        txtUsername.setPreferredSize(new java.awt.Dimension(200, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(txtUsername, gridBagConstraints);

        lblPassword.setText("Palavra Passe");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 2, 0);
        add(lblPassword, gridBagConstraints);

        btnNext.setText("Avançar");
        btnNext.setActionCommand(ACTION_DO_LOGIN);
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        add(btnNext, gridBagConstraints);

        passField.setPreferredSize(new java.awt.Dimension(150, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(passField, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
    	// Action forward
    	fireActionPerformed(evt);
    }//GEN-LAST:event_btnNextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JPasswordField passField;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

}
