/*
 * LoginBox.java created on Mar 10, 2009
 *
 * Copyright 2009 HFernandes. All rights reserved.
 * HFernandes PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */

package com.linkare.rec.impl.newface.component;

import com.linkare.rec.impl.newface.utils.LAFConnector;
import java.awt.Color;
import java.util.logging.Logger;

import javax.swing.JPasswordField;
import javax.swing.UIManager;

import com.linkare.rec.impl.newface.utils.LAFConnector.SpecialELabProperties;

/**
 *
 * @author hfernandes
 */
public class SimpleLoginBox extends GradientPane {

    private static final long serialVersionUID = 698114786085470559L;
    
    @SuppressWarnings("unused")
	private static final Logger log = Logger.getLogger(SimpleLoginBox.class.getName());
    
    /**
	 * The LOGIN action identifier.
	 */
	public static final String ACTION_DO_LOGIN = SimpleLoginBox.class.getSimpleName() + "_ACTION_LOGIN";
	
	/** Creates new form LoginBox */
	public SimpleLoginBox() {
		super(GradientStyle.VERTICAL_LINEAR_DARK_TO_LIGHT);

		initComponents();
		customInit();
	}

	private void customInit() {
		Color fgColor = UIManager.getColor(SpecialELabProperties.ENABLED_FOREGROUND_ON_DARK.getName());
		if (fgColor != null) {
			lblUserName.setForeground(fgColor);
			//lblPassword.setForeground(fgColor);
		}
	}
	
	/**
	 * @return the username
	 */
	public String getUsername() {
		return txtUsername.getText();
	}
	
	/**
	 * @see JPasswordField#getPassword()
	 * @return the password text
	 */
	public String getPassword() {
		//return new String(passField.getPassword());
        return null;
	}

    // FIXME Let a component override the elab default laf behaviour

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblUserName = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        btnNext = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        setPreferredSize(new java.awt.Dimension(360, 160));
        setLayout(new java.awt.GridBagLayout());

        lblUserName.setForeground(LAFConnector.getColor(SpecialELabProperties.SELECTION_FOREGROUND_ON_DARK));
        lblUserName.setText("Indique um nome de utilizador");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 2, 0);
        add(lblUserName, gridBagConstraints);

        txtUsername.setPreferredSize(new java.awt.Dimension(215, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(txtUsername, gridBagConstraints);

        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/linkare/rec/impl/newface/component/resources/avancar.jpg"))); // NOI18N
        btnNext.setActionCommand(ACTION_DO_LOGIN);
        btnNext.setBorder(null);
        btnNext.setBorderPainted(false);
        btnNext.setContentAreaFilled(false);
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        add(btnNext, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
    	// Action forward
    	fireActionPerformed(evt);
    }//GEN-LAST:event_btnNextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

}
