/* 
 * ReCView.java created on Jan 30, 2009
 * 
 * Copyright 2009 Linkare TI. All rights reserved.
 * Linkare TI PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */

package com.linkare.rec.impl.newface;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Logger;

import com.linkare.rec.impl.newface.component.GlassPane;
import com.linkare.rec.impl.newface.component.LoginBox;
import com.linkare.rec.impl.newface.component.MessageBox;
import com.linkare.rec.impl.newface.component.UndecoratedDialog;
import com.linkare.rec.impl.newface.component.GlassPane.CatchEvents;
import com.linkare.rec.impl.newface.config.ReCFaceConfig;


/**
 * The entry Frame to the ReC Application.
 * 
 * @author Henrique Fenandes
 */
public class ReCView extends javax.swing.JFrame implements ActionListener {

    private static final long serialVersionUID = -8746255689938838099L;
    
    @SuppressWarnings("unused")
	private static final Logger log = Logger.getLogger(ReCView.class.getName());
    
    /**
	 * The SHOW_LOGIN_BOX action identifier.
	 */
	public static final String ACTION_SHOW_LOGIN_BOX = ReCView.class.getSimpleName() + "_ACTION_SHOW_LOGIN_BOX";
    
    /**
     * The ReC configuration.
     */
    private ReCFaceConfig faceConfig;

    /**
     * The glass pane.
     */
    private static final GlassPane GLASS_PANE = new GlassPane(CatchEvents.ALL);
    
    /**
     * The LoginBox
     */
    private UndecoratedDialog<LoginBox> loginDialog;
    
    /**
     * The messagebox
     */
    private UndecoratedDialog<MessageBox> messageBox;

	/**
	 * Creates new form ReCFrame
	 * 
	 * @param faceConfig
	 */
	public ReCView(ReCFaceConfig faceConfig) {
		this.faceConfig = faceConfig;

		initComponents();
		customInit();
	}

	/**
	 * @param faceConfig
	 */
	private void customInit() {
		
		// LoginBox Dialog
		loginDialog = new UndecoratedDialog<LoginBox>(new LoginBox(), this);
		loginDialog.getContent().addActionListener(this);
		
		// MessageBox Dialog
		messageBox = new UndecoratedDialog<MessageBox>(new MessageBox(), this);
		
		// Toolbar
		btnLogin.addActionListener(this);
		
		// ReCView (This Frame)
		setGlassPane(GLASS_PANE);
		setPreferredSize(new Dimension(faceConfig.getAppPreferredWidth(), faceConfig.getAppPreferredHeight()));
		pack();
		setLocationRelativeTo(null);
	}

    /**
     * @return the faceConfig
     */
    public ReCFaceConfig getFaceConfig() {
        return faceConfig;
    }
    
    /*
     * Actions Handler 
     */
    @Override
	public void actionPerformed(ActionEvent evt) {
    	String action = evt.getActionCommand();
    	
    	if (ReCView.ACTION_SHOW_LOGIN_BOX.equals(action)) {
    		getGlassPane().setVisible(true);
        	loginDialog.setVisible(true);
        	
    	} else if (LoginBox.ACTION_DO_LOGIN.equals(action)) {
			// TODO login
			
			//getGlassPane().setVisible(visible);
	    	loginDialog.setVisible(false);
	    	
	    	messageBox.getContent().setMessage("A ligar ao ELab...");
	    	messageBox.setVisible(true);
		}
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolBar = new com.linkare.rec.impl.newface.component.ToolBar();
        leftSpace = new com.linkare.rec.impl.newface.component.Spacer();
        btnLogin = new com.linkare.rec.impl.newface.component.ToolBarButton();
        layoutContainerPane = new com.linkare.rec.impl.newface.component.LayoutContainerPane();
        menuBar = new com.linkare.rec.impl.newface.component.MenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("ReCViewFrame"); // NOI18N

        toolBar.setPreferredSize(new java.awt.Dimension(8, 31));

        leftSpace.setMaximumSize(new java.awt.Dimension(8, 21));
        leftSpace.setPreferredSize(new java.awt.Dimension(8, 21));
        toolBar.add(leftSpace);

        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/linkare/rec/impl/newface/resources/on.gif"))); // NOI18N
        btnLogin.setActionCommand(ACTION_SHOW_LOGIN_BOX);
        btnLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(btnLogin);

        getContentPane().add(toolBar, java.awt.BorderLayout.PAGE_START);
        getContentPane().add(layoutContainerPane, java.awt.BorderLayout.CENTER);

        menuBar.setPreferredSize(new java.awt.Dimension(291, 31));
        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.linkare.rec.impl.newface.component.ToolBarButton btnLogin;
    private com.linkare.rec.impl.newface.component.LayoutContainerPane layoutContainerPane;
    private com.linkare.rec.impl.newface.component.Spacer leftSpace;
    private com.linkare.rec.impl.newface.component.MenuBar menuBar;
    private com.linkare.rec.impl.newface.component.ToolBar toolBar;
    // End of variables declaration//GEN-END:variables

}
