version: '3'
services:
  nginx:
    build:
      context: streamer
    image: ${repo}/${simplifiedGroupId}/${artifactId}/streamer:${project.version}
  webswing:
    build:
      context: webswing
    image: ${repo}/${simplifiedGroupId}/${artifactId}/webswing-${webswing.version}-${openjdk.version}:${project.version}
  payara:
    build:
      context: payara
    image: ${repo}/${simplifiedGroupId}/${artifactId}/payara-${payara.docker.version}:${project.version}
  openjdk11:
    build:
      context: openjdk11
    image: ${repo}/${simplifiedGroupId}/${artifactId}/openjdk-${openjdk.docker.version}:${project.version}
  # httpd:
  #   build:
  #     context: httpd
  #   image: ${repo}/${simplifiedGroupId}/httpd-${httpd.version}:${project.version}
  #webswing-admin:
  #  build:
  #    context: webswing-admin
  #  image: ${repo}/${simplifiedGroupId}/${artifactId}/webswing-admin-${webswing.version}-${openjdk.version}:${project.version}
  traefik:
    build:
      context: traefik
    image: ${repo}/${simplifiedGroupId}/${artifactId}/traefik-${traefik.version}:${project.version}