/*
 * JPanelDigital.java
 *
 * Created on 9 de Abril de 2003, 20:31
 */

package pt.utl.ist.elab.client.webrobot.displays.auxUi;

import com.linkare.rec.impl.client.experiment.*;
import com.linkare.rec.data.acquisition.*;
import com.linkare.rec.data.metadata.*;
import com.linkare.rec.data.config.*;

/**
 *
 * @author  Andr�
 */
public class JPanelDigital extends javax.swing.JPanel implements ExpDataModelListener
{
    
    /** Creates new form JPanelDigital */
    public JPanelDigital() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jRadioButtonB0 = new javax.swing.JRadioButton();
        jRadioButtonB1 = new javax.swing.JRadioButton();
        jRadioButtonB2 = new javax.swing.JRadioButton();
        jRadioButtonB3 = new javax.swing.JRadioButton();
        jRadioButtonB4 = new javax.swing.JRadioButton();
        jRadioButtonB5 = new javax.swing.JRadioButton();
        jRadioButtonB6 = new javax.swing.JRadioButton();
        jRadioButtonB7 = new javax.swing.JRadioButton();
        jLabelB0 = new javax.swing.JLabel();
        jLabelB1 = new javax.swing.JLabel();
        jLabelB2 = new javax.swing.JLabel();
        jLabelB3 = new javax.swing.JLabel();
        jLabelB4 = new javax.swing.JLabel();
        jLabelB5 = new javax.swing.JLabel();
        jLabelB6 = new javax.swing.JLabel();
        jLabelB7 = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        jRadioButtonB0.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jRadioButtonB0.setForeground(new java.awt.Color(0, 51, 153));
        jRadioButtonB0.setFocusable(false);
        jRadioButtonB0.setRequestFocusEnabled(false);
        jRadioButtonB0.setVerifyInputWhenFocusTarget(false);
        jRadioButtonB0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonB0ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(40, 10, 0, 0);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        add(jRadioButtonB0, gridBagConstraints);

        jRadioButtonB1.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jRadioButtonB1.setForeground(new java.awt.Color(0, 51, 153));
        jRadioButtonB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonB1ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(40, 3, 0, 0);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        add(jRadioButtonB1, gridBagConstraints);

        jRadioButtonB2.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jRadioButtonB2.setForeground(new java.awt.Color(0, 51, 153));
        jRadioButtonB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonB2ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(40, 4, 0, 0);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        add(jRadioButtonB2, gridBagConstraints);

        jRadioButtonB3.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jRadioButtonB3.setForeground(new java.awt.Color(0, 51, 153));
        jRadioButtonB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonB3ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(40, 4, 0, 0);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        add(jRadioButtonB3, gridBagConstraints);

        jRadioButtonB4.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jRadioButtonB4.setForeground(new java.awt.Color(0, 51, 153));
        jRadioButtonB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonB4ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(40, 4, 0, 0);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        add(jRadioButtonB4, gridBagConstraints);

        jRadioButtonB5.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jRadioButtonB5.setForeground(new java.awt.Color(0, 51, 153));
        jRadioButtonB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonB5ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(40, 4, 0, 0);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        add(jRadioButtonB5, gridBagConstraints);

        jRadioButtonB6.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jRadioButtonB6.setForeground(new java.awt.Color(0, 51, 153));
        jRadioButtonB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonB6ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(40, 4, 0, 0);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        add(jRadioButtonB6, gridBagConstraints);

        jRadioButtonB7.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jRadioButtonB7.setForeground(new java.awt.Color(0, 51, 153));
        jRadioButtonB7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonB7ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(40, 4, 0, 0);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        add(jRadioButtonB7, gridBagConstraints);

        jLabelB0.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabelB0.setForeground(new java.awt.Color(0, 51, 153));
        jLabelB0.setText("b0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(25, 13, 0, 0);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        add(jLabelB0, gridBagConstraints);

        jLabelB1.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabelB1.setForeground(new java.awt.Color(0, 51, 153));
        jLabelB1.setText("b1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(25, 1, 0, 0);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        add(jLabelB1, gridBagConstraints);

        jLabelB2.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabelB2.setForeground(new java.awt.Color(0, 51, 153));
        jLabelB2.setText("b2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(25, 1, 0, 0);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        add(jLabelB2, gridBagConstraints);

        jLabelB3.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabelB3.setForeground(new java.awt.Color(0, 51, 153));
        jLabelB3.setText("b3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(25, 1, 0, 0);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        add(jLabelB3, gridBagConstraints);

        jLabelB4.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabelB4.setForeground(new java.awt.Color(0, 51, 153));
        jLabelB4.setText("b4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(25, 1, 0, 0);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        add(jLabelB4, gridBagConstraints);

        jLabelB5.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabelB5.setForeground(new java.awt.Color(0, 51, 153));
        jLabelB5.setText("b5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(25, 1, 0, 0);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        add(jLabelB5, gridBagConstraints);

        jLabelB6.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabelB6.setForeground(new java.awt.Color(0, 51, 153));
        jLabelB6.setText("b6");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(25, 1, 0, 0);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        add(jLabelB6, gridBagConstraints);

        jLabelB7.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabelB7.setForeground(new java.awt.Color(0, 51, 153));
        jLabelB7.setText("b7");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(25, 1, 0, 0);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        add(jLabelB7, gridBagConstraints);

    }//GEN-END:initComponents

    private void jRadioButtonB7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonB7ActionPerformed
        undoUserSelection(jRadioButtonB7);
    }//GEN-LAST:event_jRadioButtonB7ActionPerformed

    private void jRadioButtonB6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonB6ActionPerformed
        undoUserSelection(jRadioButtonB6);
    }//GEN-LAST:event_jRadioButtonB6ActionPerformed

    private void jRadioButtonB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonB5ActionPerformed
        undoUserSelection(jRadioButtonB5);
    }//GEN-LAST:event_jRadioButtonB5ActionPerformed

    private void jRadioButtonB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonB4ActionPerformed
        undoUserSelection(jRadioButtonB4);
    }//GEN-LAST:event_jRadioButtonB4ActionPerformed

    private void jRadioButtonB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonB3ActionPerformed
        undoUserSelection(jRadioButtonB3);
    }//GEN-LAST:event_jRadioButtonB3ActionPerformed

    private void jRadioButtonB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonB2ActionPerformed
        undoUserSelection(jRadioButtonB2);
    }//GEN-LAST:event_jRadioButtonB2ActionPerformed

    private void jRadioButtonB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonB1ActionPerformed
        undoUserSelection(jRadioButtonB1);
    }//GEN-LAST:event_jRadioButtonB1ActionPerformed

    private void jRadioButtonB0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonB0ActionPerformed
        undoUserSelection(jRadioButtonB0);
    }//GEN-LAST:event_jRadioButtonB0ActionPerformed

    private void undoUserSelection(javax.swing.JRadioButton jRadioButton)
    {
        if(jRadioButton.isSelected())
        {
            jRadioButton.setSelected(false);
        }
        else
        {
            jRadioButton.setSelected(true);
        }
    }
    
    /** Getter for property b0.
     * @return Value of property b0.
     */
    public boolean isB0() {
        return this.b0;
    }    
    
    /** Setter for property b0.
     * @param b0 New value of property b0.
     */
    public void setB0(boolean b0) {
        this.b0 = b0;
        jRadioButtonB0.setSelected(b0);
    }    
    
    /** Getter for property b1.
     * @return Value of property b1.
     */
    public boolean isB1() {
        return this.b1;
    }
    
    /** Setter for property b1.
     * @param b1 New value of property b1.
     */
    public void setB1(boolean b1) {
        this.b1 = b1;
        jRadioButtonB1.setSelected(b1);
    }
    
    /** Getter for property b2.
     * @return Value of property b2.
     */
    public boolean isB2() {
        return this.b2;
    }
    
    /** Setter for property b2.
     * @param b2 New value of property b2.
     */
    public void setB2(boolean b2) {
        this.b2 = b2;
        jRadioButtonB2.setSelected(b2);
    }
    
    /** Getter for property b3.
     * @return Value of property b3.
     */
    public boolean isB3() {
        return b3;
    }
    
    /** Setter for property b3.
     * @param b3 New value of property b3.
     */
    public void setB3(boolean b3) {
        this.b3=b3;
        jRadioButtonB3.setSelected(b3);
    }
    
    /** Getter for property b4.
     * @return Value of property b4.
     */
    public boolean isB4() {
        return b4;
    }
    
    /** Setter for property b4.
     * @param b4 New value of property b4.
     */
    public void setB4(boolean b4) {
        this.b4=b4;
    }
    
    /** Getter for property b5.
     * @return Value of property b5.
     */
    public boolean isB5() {
        return b5;
    }
    
    /** Setter for property b5.
     * @param b5 New value of property b5.
     */
    public void setB5(boolean b5) {
        this.b5=b5;
    }
    
    /** Getter for property b6.
     * @return Value of property b6.
     */
    public boolean isB6() {
        return b6;
    }
    
    /** Setter for property b6.
     * @param b6 New value of property b6.
     */
    public void setB6(boolean b6) {
        this.b6=b6;
        jRadioButtonB6.setSelected(b6);
    }
    
    /** Getter for property b7.
     * @return Value of property b7.
     */
    public boolean isB7() {
        return b7;
    }
    
    /** Setter for property b7.
     * @param b7 New value of property b7.
     */
    public void setB7(boolean b7) {
        this.b7=b7;
        jRadioButtonB7.setSelected(b7);
    }
    
    public void dataModelRunning() {
    }
    
    public void dataModelStoped() {
    }
    
    public void headerAvailable(HardwareAcquisitionConfig header) {
    }
    
    public void newSamples(NewExpDataEvent evt) 
    {
        int lastSample=evt.getSamplesEndIndex();        
        setB0(model.getValueAt(lastSample,8).getValue().isBooleanValue());
        setB1(model.getValueAt(lastSample,9).getValue().isBooleanValue());
        setB2(model.getValueAt(lastSample,10).getValue().isBooleanValue());
        setB3(model.getValueAt(lastSample,11).getValue().isBooleanValue());
        setB4(model.getValueAt(lastSample,12).getValue().isBooleanValue());
        setB5(model.getValueAt(lastSample,13).getValue().isBooleanValue());
        setB6(model.getValueAt(lastSample,14).getValue().isBooleanValue());
        setB7(model.getValueAt(lastSample,15).getValue().isBooleanValue());        
    }
    
    public void setExpDataModel(ExpDataModel model) 
    {
        if(this.model!=null)
        {
	    model.removeExpDataModelListener(this);
        }
	
	this.model=model;
	
	if(this.model!=null)
        {
	    this.model.addExpDataModelListener(this);	
        }
    }    
    
    public void dataModelEnded()
    {
    }
    
    public void dataModelError()
    {
    }
    
    public void dataModelStarted()
    {
        headerAvailable(model.getAcquisitionConfig());
    }
    
    public void dataModelStartedNoData()
    {
    }
    
    public void dataModelWaiting()
    {
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelB2;
    private javax.swing.JLabel jLabelB0;
    private javax.swing.JRadioButton jRadioButtonB4;
    private javax.swing.JRadioButton jRadioButtonB7;
    private javax.swing.JLabel jLabelB3;
    private javax.swing.JLabel jLabelB5;
    private javax.swing.JLabel jLabelB6;
    private javax.swing.JRadioButton jRadioButtonB2;
    private javax.swing.JRadioButton jRadioButtonB1;
    private javax.swing.JLabel jLabelB7;
    private javax.swing.JLabel jLabelB4;
    private javax.swing.JLabel jLabelB1;
    private javax.swing.JRadioButton jRadioButtonB3;
    private javax.swing.JRadioButton jRadioButtonB6;
    private javax.swing.JRadioButton jRadioButtonB5;
    private javax.swing.JRadioButton jRadioButtonB0;
    // End of variables declaration//GEN-END:variables

    private ExpDataModel model=null;
    
    /** Holds value of property b0. */
    private boolean b0=false;    
    
    /** Holds value of property b1. */
    private boolean b1=false;

    /** Holds value of property b2. */
    private boolean b2=false;
    
    /** Holds value of property b3. */
    private boolean b3=false;

    /** Holds value of property b4. */
    private boolean b4=false;    
    
    /** Holds value of property b5. */
    private boolean b5=false;
    
    /** Holds value of property b6. */
    private boolean b6=false;

    /** Holds value of property b7. */
    private boolean b7=false;    
}
