/*
 * Laffy - Swing Look and Feel Sampler
 * Copyright (C) Sun Microsystems
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA
 */

package org.jdesktop.laffy.buttons;

import org.jdesktop.laffy.I18nResourceHandler;
import org.jdesktop.laffy.OptionsSettablePanel;

import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.plaf.basic.BasicRadioButtonUI;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/** @author Jasper Potts */
public class RadioPanel extends OptionsSettablePanel {
    private final Color DEFAULT_BACKGROUND;
    private final boolean DEFAULT_OPAQUE;

    /** Creates new form RadioPanel */
    public RadioPanel() {
	initComponents();
	DEFAULT_BACKGROUND = oRadioButton.getBackground();
	DEFAULT_OPAQUE = oRadioButton.isOpaque();
	oRadioButton.setModel(new ButtonPanel.OverButtonModel());
	pRadioButton.setModel(new ButtonPanel.PressedButtonModel());
	foRadioButton.setModel(new ButtonPanel.OverButtonModel());
	fpRadioButton.setModel(new ButtonPanel.PressedButtonModel());
	soRadioButton.setModel(new ButtonPanel.OverSelectedButtonModel());
	spRadioButton.setModel(new ButtonPanel.PressedSelectedButtonModel());
	sfoRadioButton.setModel(new ButtonPanel.OverSelectedButtonModel());
	sfpRadioButton.setModel(new ButtonPanel.PressedSelectedButtonModel());
	// apply to all buttons
	ActionListener actionListener = new ActionListener() {
	    public void actionPerformed(ActionEvent e) {
		JOptionPane.showMessageDialog(RadioPanel.this, "Button Clicked!");
	    }
	};
	for (Component component : getComponents()) {
	    if (component instanceof JRadioButton) {
		((JRadioButton) component).addActionListener(actionListener);
	    }
	}
    }

    // =================================================================================================================
    // OptionsSettablePanel Methods

    @Override
    public void setForceComponentsBackgroundColor(boolean force) {
	Color c = force ? FORCED_BACKGROUND : DEFAULT_BACKGROUND;
	// apply to all buttons
	for (Component component : getComponents()) {
	    if (component instanceof JRadioButton) {
		component.setBackground(c);
	    }
	}
    }

    @Override
    public void setForceComponentsNonOpaque(boolean force) {
	setBackground(force ? Color.GREEN : DEFAULT_BACKGROUND);
	boolean o = force ? false : DEFAULT_OPAQUE;
	// apply to all buttons
	for (Component component : getComponents()) {
	    if (component instanceof JRadioButton) {
		((JRadioButton) component).setOpaque(o);
	    }
	}
    }

    @Override
    public void setForceComponentsToBasicUI(boolean force) {
	for (Component component : getComponents()) {
	    if (component instanceof JRadioButton) {
		if (force) {
		    ((JRadioButton) component).setUI(new BasicRadioButtonUI());
		} else {
		    ((JRadioButton) component).updateUI();
		}
	    }
	}
	revalidate();
    }

    // =================================================================================================================
    // Netbeans Code

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
	java.awt.GridBagConstraints gridBagConstraints;

	jLabel8 = new javax.swing.JLabel();
	jLabel2 = new javax.swing.JLabel();
	jLabel3 = new javax.swing.JLabel();
	jLabel4 = new javax.swing.JLabel();
	jLabel1 = new javax.swing.JLabel();
	jLabel5 = new javax.swing.JLabel();
	jLabel7 = new javax.swing.JLabel();
	jLabel6 = new javax.swing.JLabel();
	jRadioButton1 = new javax.swing.JRadioButton();
	oRadioButton = new javax.swing.JRadioButton();
	pRadioButton = new javax.swing.JRadioButton();
	jRadioButton4 = new javax.swing.JRadioButton();
	jRadioButton5 = new JRadioButton() {
	    public boolean isFocusPainted() {
		return true;
	    }

	    public boolean isFocusOwner() {
		return true;
	    }
	};
	jRadioButton6 = new javax.swing.JRadioButton();
	foRadioButton = new JRadioButton() {
	    public boolean isFocusPainted() {
		return true;
	    }

	    public boolean isFocusOwner() {
		return true;
	    }
	};
	fpRadioButton = new JRadioButton() {
	    public boolean isFocusPainted() {
		return true;
	    }

	    public boolean isFocusOwner() {
		return true;
	    }
	};
	jRadioButton9 = new JRadioButton() {
	    public boolean isFocusPainted() {
		return true;
	    }

	    public boolean isFocusOwner() {
		return true;
	    }
	};
	sfoRadioButton = new JRadioButton() {
	    public boolean isFocusPainted() {
		return true;
	    }

	    public boolean isFocusOwner() {
		return true;
	    }
	};
	sfpRadioButton = new JRadioButton() {
	    public boolean isFocusPainted() {
		return true;
	    }

	    public boolean isFocusOwner() {
		return true;
	    }
	};
	soRadioButton = new javax.swing.JRadioButton();
	spRadioButton = new javax.swing.JRadioButton();
	jRadioButton14 = new javax.swing.JRadioButton();

	setLayout(new java.awt.GridBagLayout());

	jLabel8.setFont(jLabel8.getFont().deriveFont(jLabel8.getFont().getStyle() | java.awt.Font.BOLD,
		jLabel8.getFont().getSize() - 2));
	jLabel8.setForeground(java.awt.Color.darkGray);
	//jLabel8.setText("Normal");
	jLabel8.setText(I18nResourceHandler.getMessage("Normal"));
	jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
	gridBagConstraints = new java.awt.GridBagConstraints();
	gridBagConstraints.gridx = 0;
	gridBagConstraints.gridy = 1;
	gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
	gridBagConstraints.insets = new java.awt.Insets(2, 5, 2, 5);
	add(jLabel8, gridBagConstraints);

	jLabel2.setFont(jLabel2.getFont().deriveFont(jLabel2.getFont().getStyle() | java.awt.Font.BOLD,
		jLabel2.getFont().getSize() - 2));
	jLabel2.setForeground(java.awt.Color.darkGray);
	//jLabel2.setText("Focused");
	jLabel2.setText(I18nResourceHandler.getMessage("Focused"));
	jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
	gridBagConstraints = new java.awt.GridBagConstraints();
	gridBagConstraints.gridx = 0;
	gridBagConstraints.gridy = 2;
	gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
	gridBagConstraints.insets = new java.awt.Insets(2, 5, 2, 5);
	add(jLabel2, gridBagConstraints);

	jLabel3.setFont(jLabel3.getFont().deriveFont(jLabel3.getFont().getStyle() | java.awt.Font.BOLD,
		jLabel3.getFont().getSize() - 2));
	jLabel3.setForeground(java.awt.Color.darkGray);
	//jLabel3.setText("Selected");
	jLabel3.setText(I18nResourceHandler.getMessage("Selected"));
	jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
	gridBagConstraints = new java.awt.GridBagConstraints();
	gridBagConstraints.gridx = 0;
	gridBagConstraints.gridy = 3;
	gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
	gridBagConstraints.insets = new java.awt.Insets(2, 5, 2, 5);
	add(jLabel3, gridBagConstraints);

	jLabel4.setFont(jLabel4.getFont().deriveFont(jLabel4.getFont().getStyle() | java.awt.Font.BOLD,
		jLabel4.getFont().getSize() - 2));
	jLabel4.setForeground(java.awt.Color.darkGray);
	//jLabel4.setText("Selected + Focused");
	jLabel4.setText(I18nResourceHandler.getMessage("Selected_+_Focused"));
	jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
	gridBagConstraints = new java.awt.GridBagConstraints();
	gridBagConstraints.gridx = 0;
	gridBagConstraints.gridy = 4;
	gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
	gridBagConstraints.insets = new java.awt.Insets(2, 5, 2, 5);
	add(jLabel4, gridBagConstraints);

	jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD,
		jLabel1.getFont().getSize() - 2));
	jLabel1.setForeground(java.awt.Color.darkGray);
	//jLabel1.setText("Normal");
	jLabel1.setText(I18nResourceHandler.getMessage("Normal"));
	jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
	gridBagConstraints = new java.awt.GridBagConstraints();
	gridBagConstraints.gridx = 1;
	gridBagConstraints.gridy = 0;
	gridBagConstraints.insets = new java.awt.Insets(4, 2, 4, 2);
	add(jLabel1, gridBagConstraints);

	jLabel5.setFont(jLabel5.getFont().deriveFont(jLabel5.getFont().getStyle() | java.awt.Font.BOLD,
		jLabel5.getFont().getSize() - 2));
	jLabel5.setForeground(java.awt.Color.darkGray);
	//jLabel5.setText("Over");
	jLabel5.setText(I18nResourceHandler.getMessage("Over"));
	jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
	gridBagConstraints = new java.awt.GridBagConstraints();
	gridBagConstraints.gridx = 2;
	gridBagConstraints.gridy = 0;
	gridBagConstraints.insets = new java.awt.Insets(4, 2, 4, 2);
	add(jLabel5, gridBagConstraints);

	jLabel7.setFont(jLabel7.getFont().deriveFont(jLabel7.getFont().getStyle() | java.awt.Font.BOLD,
		jLabel7.getFont().getSize() - 2));
	jLabel7.setForeground(java.awt.Color.darkGray);
	//jLabel7.setText("Pressed");
	jLabel7.setText(I18nResourceHandler.getMessage("Pressed"));
	jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
	gridBagConstraints = new java.awt.GridBagConstraints();
	gridBagConstraints.gridx = 3;
	gridBagConstraints.gridy = 0;
	gridBagConstraints.insets = new java.awt.Insets(4, 2, 4, 2);
	add(jLabel7, gridBagConstraints);

	jLabel6.setFont(jLabel6.getFont().deriveFont(jLabel6.getFont().getStyle() | java.awt.Font.BOLD,
		jLabel6.getFont().getSize() - 2));
	jLabel6.setForeground(java.awt.Color.darkGray);
	//jLabel6.setText("Disabled");
	jLabel6.setText(I18nResourceHandler.getMessage("Disabled"));
	jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
	gridBagConstraints = new java.awt.GridBagConstraints();
	gridBagConstraints.gridx = 4;
	gridBagConstraints.gridy = 0;
	gridBagConstraints.insets = new java.awt.Insets(4, 2, 4, 2);
	add(jLabel6, gridBagConstraints);

	jRadioButton1.setMnemonic('2');
	//jRadioButton1.setText("Cancel");
	jRadioButton1.setText(I18nResourceHandler.getMessage("Cancel"));
	gridBagConstraints = new java.awt.GridBagConstraints();
	gridBagConstraints.gridx = 1;
	gridBagConstraints.gridy = 1;
	gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
	gridBagConstraints.weightx = 1.0;
	gridBagConstraints.weighty = 1.0;
	gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
	add(jRadioButton1, gridBagConstraints);

	oRadioButton.setMnemonic('2');
	//oRadioButton.setText("Cancel");
	oRadioButton.setText(I18nResourceHandler.getMessage("Cancel"));
	gridBagConstraints = new java.awt.GridBagConstraints();
	gridBagConstraints.gridx = 2;
	gridBagConstraints.gridy = 1;
	gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
	gridBagConstraints.weightx = 1.0;
	gridBagConstraints.weighty = 1.0;
	gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
	add(oRadioButton, gridBagConstraints);

	pRadioButton.setMnemonic('2');
	//pRadioButton.setText("Cancel");
	pRadioButton.setText(I18nResourceHandler.getMessage("Cancel"));
	gridBagConstraints = new java.awt.GridBagConstraints();
	gridBagConstraints.gridx = 3;
	gridBagConstraints.gridy = 1;
	gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
	gridBagConstraints.weightx = 1.0;
	gridBagConstraints.weighty = 1.0;
	gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
	add(pRadioButton, gridBagConstraints);

	jRadioButton4.setMnemonic('2');
	//jRadioButton4.setText("Cancel");
	jRadioButton4.setText(I18nResourceHandler.getMessage("Cancel"));
	jRadioButton4.setEnabled(false);
	gridBagConstraints = new java.awt.GridBagConstraints();
	gridBagConstraints.gridx = 4;
	gridBagConstraints.gridy = 1;
	gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
	gridBagConstraints.weightx = 1.0;
	gridBagConstraints.weighty = 1.0;
	gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
	add(jRadioButton4, gridBagConstraints);

	jRadioButton5.setMnemonic('2');
	//jRadioButton5.setText("Cancel");
	jRadioButton5.setText(I18nResourceHandler.getMessage("Cancel"));
	gridBagConstraints = new java.awt.GridBagConstraints();
	gridBagConstraints.gridx = 1;
	gridBagConstraints.gridy = 2;
	gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
	gridBagConstraints.weightx = 1.0;
	gridBagConstraints.weighty = 1.0;
	gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
	add(jRadioButton5, gridBagConstraints);

	jRadioButton6.setMnemonic('2');
	jRadioButton6.setSelected(true);
	//jRadioButton6.setText("Cancel");
	jRadioButton6.setText(I18nResourceHandler.getMessage("Cancel"));
	gridBagConstraints = new java.awt.GridBagConstraints();
	gridBagConstraints.gridx = 1;
	gridBagConstraints.gridy = 3;
	gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
	gridBagConstraints.weightx = 1.0;
	gridBagConstraints.weighty = 1.0;
	gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
	add(jRadioButton6, gridBagConstraints);

	foRadioButton.setMnemonic('2');
	//foRadioButton.setText("Cancel");
	foRadioButton.setText(I18nResourceHandler.getMessage("Cancel"));
	gridBagConstraints = new java.awt.GridBagConstraints();
	gridBagConstraints.gridx = 2;
	gridBagConstraints.gridy = 2;
	gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
	gridBagConstraints.weightx = 1.0;
	gridBagConstraints.weighty = 1.0;
	gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
	add(foRadioButton, gridBagConstraints);

	fpRadioButton.setMnemonic('2');
	//fpRadioButton.setText("Cancel");
	fpRadioButton.setText(I18nResourceHandler.getMessage("Cancel"));
	gridBagConstraints = new java.awt.GridBagConstraints();
	gridBagConstraints.gridx = 3;
	gridBagConstraints.gridy = 2;
	gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
	gridBagConstraints.weightx = 1.0;
	gridBagConstraints.weighty = 1.0;
	gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
	add(fpRadioButton, gridBagConstraints);

	jRadioButton9.setMnemonic('2');
	jRadioButton9.setSelected(true);
	//jRadioButton9.setText("Cancel");
	jRadioButton9.setText(I18nResourceHandler.getMessage("Cancel"));
	gridBagConstraints = new java.awt.GridBagConstraints();
	gridBagConstraints.gridx = 1;
	gridBagConstraints.gridy = 4;
	gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
	gridBagConstraints.weightx = 1.0;
	gridBagConstraints.weighty = 1.0;
	gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
	add(jRadioButton9, gridBagConstraints);

	sfoRadioButton.setMnemonic('2');
	sfoRadioButton.setSelected(true);
	//sfoRadioButton.setText("Cancel");
	sfoRadioButton.setText(I18nResourceHandler.getMessage("Cancel"));
	gridBagConstraints = new java.awt.GridBagConstraints();
	gridBagConstraints.gridx = 2;
	gridBagConstraints.gridy = 4;
	gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
	gridBagConstraints.weightx = 1.0;
	gridBagConstraints.weighty = 1.0;
	gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
	add(sfoRadioButton, gridBagConstraints);

	sfpRadioButton.setMnemonic('2');
	sfpRadioButton.setSelected(true);
	//sfpRadioButton.setText("Cancel");
	sfpRadioButton.setText(I18nResourceHandler.getMessage("Cancel"));
	gridBagConstraints = new java.awt.GridBagConstraints();
	gridBagConstraints.gridx = 3;
	gridBagConstraints.gridy = 4;
	gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
	gridBagConstraints.weightx = 1.0;
	gridBagConstraints.weighty = 1.0;
	gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
	add(sfpRadioButton, gridBagConstraints);

	soRadioButton.setMnemonic('2');
	soRadioButton.setSelected(true);
	//soRadioButton.setText("Cancel");
	soRadioButton.setText(I18nResourceHandler.getMessage("Cancel"));
	gridBagConstraints = new java.awt.GridBagConstraints();
	gridBagConstraints.gridx = 2;
	gridBagConstraints.gridy = 3;
	gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
	gridBagConstraints.weightx = 1.0;
	gridBagConstraints.weighty = 1.0;
	gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
	add(soRadioButton, gridBagConstraints);

	spRadioButton.setMnemonic('2');
	spRadioButton.setSelected(true);
	//spRadioButton.setText("Cancel");
	spRadioButton.setText(I18nResourceHandler.getMessage("Cancel"));
	gridBagConstraints = new java.awt.GridBagConstraints();
	gridBagConstraints.gridx = 3;
	gridBagConstraints.gridy = 3;
	gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
	gridBagConstraints.weightx = 1.0;
	gridBagConstraints.weighty = 1.0;
	gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
	add(spRadioButton, gridBagConstraints);

	jRadioButton14.setMnemonic('2');
	jRadioButton14.setSelected(true);
	//jRadioButton14.setText("Cancel");
	jRadioButton14.setText(I18nResourceHandler.getMessage("Cancel"));
	jRadioButton14.setEnabled(false);
	gridBagConstraints = new java.awt.GridBagConstraints();
	gridBagConstraints.gridx = 4;
	gridBagConstraints.gridy = 3;
	gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
	gridBagConstraints.weightx = 1.0;
	gridBagConstraints.weighty = 1.0;
	gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
	add(jRadioButton14, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton foRadioButton;
    private javax.swing.JRadioButton fpRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JRadioButton oRadioButton;
    private javax.swing.JRadioButton pRadioButton;
    private javax.swing.JRadioButton sfoRadioButton;
    private javax.swing.JRadioButton sfpRadioButton;
    private javax.swing.JRadioButton soRadioButton;
    private javax.swing.JRadioButton spRadioButton;
    // End of variables declaration//GEN-END:variables

}
