package com.linkare.rec.acquisition;


/**
* com/linkare/rec/acquisition/MultiCastControllerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from I:/Projects/REC/IdlCompile/ReC7.idl
* Sabado, 17 de Janeiro de 2004 19H00m GMT
*/

public interface MultiCastControllerOperations 
{

  //version 5 - check permissions before givin' out the Hardware List
  com.linkare.rec.acquisition.MultiCastHardware[] enumerateHardware (com.linkare.rec.acquisition.UserInfo user) throws com.linkare.rec.acquisition.NotRegistered, com.linkare.rec.acquisition.NotAuthorized;
  void registerDataClient (com.linkare.rec.acquisition.DataClient data_client) throws com.linkare.rec.acquisition.MaximumClientsReached, com.linkare.rec.acquisition.NotAuthorized;

  //version 5 added suport for messages
  com.linkare.rec.acquisition.UserInfo[] getClientList (com.linkare.rec.acquisition.UserInfo user) throws com.linkare.rec.acquisition.NotRegistered, com.linkare.rec.acquisition.NotAuthorized;

  //version 5 added suport for messages
  void sendMessage (com.linkare.rec.acquisition.UserInfo user, String clientTo, String message) throws com.linkare.rec.acquisition.NotRegistered, com.linkare.rec.acquisition.NotAuthorized;

  //Version 7.0 Addition - Trying to remove dependy on NameService
  void registerHardware (com.linkare.rec.acquisition.Hardware hardware);
} // interface MultiCastControllerOperations
