/*
 * ApparatusTabbedPane.java created on May 20, 2009
 *
 * Copyright 2009 HFernandes. All rights reserved.
 * HFernandes PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */

package com.linkare.rec.impl.newface.component;

import javax.swing.JComponent;

/**
 *
 * @author hfernandes
 */
public class ApparatusTabbedPane extends javax.swing.JPanel {

    public static final int TAB_DESCRIPTION = 0;

    public static final int TAB_CUSTOMIZER = 1;

    public static final int TAB_RESULTS = 2;

    public static final int TAB_USERS = 3;


    /** Creates new form ApparatusTabbedPane */
    public ApparatusTabbedPane() {
        initComponents();
    }

    public ApparatusDescriptionPane getDescriptionPane() {
    	return descriptionPane;
    }
    
    public ApparatusUserList getApparatusUserList(){
    	return apparatusUserList1;
    }
    
	public com.linkare.rec.impl.newface.component.ExperimentActionBar getExperimentActionBar() {
		return experimentActionBar;
	}

	public void addCustomizerComponent(JComponent controller) {
    	controllerHolderScrollPane.setViewportView(controller);
    }
    
    public void setSelectedTabIndex(int index) {
    	tabbedPane.setSelectedIndex(index);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        descriptionPane = new com.linkare.rec.impl.newface.component.ApparatusDescriptionPane();
        controllerHolderPane = new javax.swing.JPanel();
        controllerHolderScrollPane = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        apparatusUserList1 = new com.linkare.rec.impl.newface.component.ApparatusUserList();
        experimentActionBar = new com.linkare.rec.impl.newface.component.ExperimentActionBar();

        setName("Form"); // NOI18N
        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        tabbedPane.setName("tabbedPane"); // NOI18N

        descriptionPane.setName("descriptionPane"); // NOI18N
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.linkare.rec.impl.newface.ReCApplication.class).getContext().getResourceMap(ApparatusTabbedPane.class);
        tabbedPane.addTab(resourceMap.getString("descriptionPane.TabConstraints.tabTitle"), resourceMap.getIcon("descriptionPane.TabConstraints.tabIcon"), descriptionPane); // NOI18N

        controllerHolderPane.setName("controllerHolderPane"); // NOI18N

        controllerHolderScrollPane.setBorder(null);
        controllerHolderScrollPane.setName("controllerHolderScrollPane"); // NOI18N
        controllerHolderScrollPane.setOpaque(false);

        javax.swing.GroupLayout controllerHolderPaneLayout = new javax.swing.GroupLayout(controllerHolderPane);
        controllerHolderPane.setLayout(controllerHolderPaneLayout);
        controllerHolderPaneLayout.setHorizontalGroup(
            controllerHolderPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controllerHolderPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(controllerHolderScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                .addContainerGap())
        );
        controllerHolderPaneLayout.setVerticalGroup(
            controllerHolderPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controllerHolderPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(controllerHolderScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbedPane.addTab(resourceMap.getString("controllerHolderPane.TabConstraints.tabTitle"), controllerHolderPane); // NOI18N

        jPanel1.setEnabled(false);
        jPanel1.setName("jPanel1"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 509, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
        );

        tabbedPane.addTab(resourceMap.getString("jPanel1.TabConstraints.tabTitle"), jPanel1); // NOI18N

        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        apparatusUserList1.setName("apparatusUserList1"); // NOI18N
        jPanel2.add(apparatusUserList1);

        tabbedPane.addTab(resourceMap.getString("jPanel2.TabConstraints.tabTitle"), jPanel2); // NOI18N

        add(tabbedPane, java.awt.BorderLayout.CENTER);

        experimentActionBar.setMinimumSize(new java.awt.Dimension(48, 10));
        experimentActionBar.setName("experimentActionBar"); // NOI18N
        add(experimentActionBar, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.linkare.rec.impl.newface.component.ApparatusUserList apparatusUserList1;
    private javax.swing.JPanel controllerHolderPane;
    private javax.swing.JScrollPane controllerHolderScrollPane;
    private com.linkare.rec.impl.newface.component.ApparatusDescriptionPane descriptionPane;
    private com.linkare.rec.impl.newface.component.ExperimentActionBar experimentActionBar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables

}
