/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MediaPane.java
 *
 * Created on 20/Abr/2009, 11:37:44
 */

package com.linkare.rec.impl.newface.component;

/**
 *
 * @author iies-consultor922
 */
public class MediaPane extends javax.swing.JPanel {

    /** Creates new form MediaPane */
    public MediaPane() {
        initComponents();
    }
    
    public ChatBox getChatBox() {
		return chatBox;
	}
    
    public VideoBox getVideoBox() {
		return videoBox;
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        videoBox = new com.linkare.rec.impl.newface.component.VideoBox();
        chatBox = new com.linkare.rec.impl.newface.component.ChatBox();
        jSeparator1 = new javax.swing.JSeparator();

        setName("Form"); // NOI18N

        videoBox.setName("videoBox"); // NOI18N

        chatBox.setName("chatBox"); // NOI18N

        jSeparator1.setName("jSeparator1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chatBox, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
            .addComponent(videoBox, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(videoBox, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chatBox, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.linkare.rec.impl.newface.component.ChatBox chatBox;
    private javax.swing.JSeparator jSeparator1;
    private com.linkare.rec.impl.newface.component.VideoBox videoBox;
    // End of variables declaration//GEN-END:variables

}
