package com.linkare.rec.acquisition;

/**
 * com/linkare/rec/acquisition/PropertyListHolder.java . Generated by the
 * IDL-to-Java compiler (portable), version "3.1" from
 * I:/Projects/REC/IdlCompile/ReC7.idl Terca-feira, 30 de Dezembro de 2003
 * 11H33m GMT
 */

// Version 7.0 Addition
public final class PropertyListHolder implements org.omg.CORBA.portable.Streamable {
	public com.linkare.rec.acquisition.Property value[] = null;

	public PropertyListHolder() {
	}

	@SuppressWarnings("PMD.ArrayIsStoredDirectly")
	public PropertyListHolder(final com.linkare.rec.acquisition.Property[] initialValue) {
		value = initialValue;
	}

	@Override
	public void _read(final org.omg.CORBA.portable.InputStream i) {
		value = com.linkare.rec.acquisition.PropertyListHelper.read(i);
	}

	@Override
	public void _write(final org.omg.CORBA.portable.OutputStream o) {
		com.linkare.rec.acquisition.PropertyListHelper.write(o, value);
	}

	@Override
	public org.omg.CORBA.TypeCode _type() {
		return com.linkare.rec.acquisition.PropertyListHelper.type();
	}

}
